import { CourseItem } from '../db';

export const seedCourses: CourseItem[] = [
  // 1-10: Online Game Development & Gaming Mastery
  {
    id: 'course-1',
    title: 'Unity 3D & C# Mobile Game Development Masterclass',
    description: 'Build high-performance 3D mobile games with Unity 2026, C# scripts, physics, particle systems, and touch controls.',
    longDescription: 'Complete step-by-step game development bootcamp. You will build 4 complete games: an endless runner, a 3D ball physics maze, an arcade space shooter, and an online multiplayer arena with Photon PUN.',
    thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=600&q=80',
    category: 'Game Development',
    type: 'course',
    accessType: 'PAID',
    price: 499,
    currency: 'BDT',
    instructor: 'Rashedul Islam',
    instructorBio: 'Lead Game Developer & Technical Artist with 8+ shipped mobile titles on Google Play and Steam.',
    durationMinutes: 720,
    totalLessons: 6,
    level: 'All Levels',
    published: true,
    skills: ['Unity 3D', 'C# Scripting', 'Mobile Game Optimization', 'Physics Engine', 'Particle FX', 'Multiplayer Networking'],
    createdAt: '2026-08-01T09:00:00.000Z',
    updatedAt: '2026-08-25T15:00:00.000Z'
  },
  {
    id: 'course-2',
    title: 'Unreal Engine 5 Action RPG & Blueprints Bootcamp',
    description: 'Master Unreal Engine 5 Nanite, Lumen dynamic lighting, combat systems, AI behavior trees, and visual blueprints.',
    longDescription: 'Create immersive third-person action RPG mechanics without writing C++. Learn character locomotion, combo attack animations, lock-on camera, inventory, quest systems, and boss AI.',
    thumbnail: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=600&q=80',
    category: 'Game Development',
    type: 'course',
    accessType: 'PAID',
    price: 650,
    currency: 'BDT',
    instructor: 'Arif Chowdhury',
    instructorBio: 'Senior Technical Designer with extensive experience in AAA visual scripting and console game production.',
    durationMinutes: 840,
    totalLessons: 5,
    level: 'Intermediate',
    published: true,
    skills: ['Unreal Engine 5', 'Blueprints', 'Lumen & Nanite', 'Combat Systems', 'Behavior Trees', 'Animation Montages'],
    createdAt: '2026-08-03T10:00:00.000Z',
    updatedAt: '2026-08-26T12:00:00.000Z'
  },
  {
    id: 'course-3',
    title: 'Godot 4.3 2D Action Platformer & GDScript Masterclass',
    description: 'Lightweight open-source 2D game development with Godot engine: tilemaps, parallax scrolling, enemies, and bosses.',
    longDescription: 'Learn GDScript from scratch and create polished retro and modern 2D games. Covers state machines, juice & screen shake, audio mixers, save games, and one-click Android APK export.',
    thumbnail: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=600&q=80',
    category: 'Game Development',
    type: 'course',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    instructor: 'Saiful Alam',
    instructorBio: 'Indie Game Creator and Open-Source Godot Evangelist.',
    durationMinutes: 420,
    totalLessons: 4,
    level: 'Beginner',
    published: true,
    skills: ['Godot 4', 'GDScript', '2D Physics', 'Tilemaps', 'AnimationPlayer', 'Mobile Export'],
    createdAt: '2026-08-05T11:00:00.000Z',
    updatedAt: '2026-08-27T14:00:00.000Z'
  },
  {
    id: 'course-4',
    title: 'Roblox Studio Lua Game Development & Monetization',
    description: 'Learn Roblox Lua scripting, datastores, custom leaderboards, pet inventory, and dev products monetization.',
    longDescription: 'Design trending Roblox tycoon and simulator games. Master server-client replication, RemoteEvents, TweenService, UI animation, and earning Robux through game passes.',
    thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=600&q=80',
    category: 'Game Development',
    type: 'course',
    accessType: 'PAID',
    price: 350,
    currency: 'BDT',
    instructor: 'Mehedi Hasan',
    instructorBio: 'Creator of top Roblox experiences with over 20M+ total play visits.',
    durationMinutes: 360,
    totalLessons: 4,
    level: 'All Levels',
    published: true,
    skills: ['Roblox Studio', 'Lua Scripting', 'DataStores', 'RemoteEvents', 'Game Monetization', 'Level Design'],
    createdAt: '2026-08-07T13:00:00.000Z',
    updatedAt: '2026-08-28T16:00:00.000Z'
  },
  {
    id: 'course-5',
    title: 'PUBG Mobile & Free Fire Esports Tactics & Aim Mastery',
    description: 'Pro gyro calibration, recoil control patterns, rotation pathing, zone prediction, and tournament communication.',
    longDescription: 'Level up your competitive gameplay. Learn 4-finger claw HUD optimization, close-range jiggle peek, sniper bullet drop calculation, and scrim clutch management from national esports champions.',
    thumbnail: 'https://images.unsplash.com/photo-1542751110-97427bbecf20?auto=format&fit=crop&w=600&q=80',
    category: 'Online Gaming & Esports',
    type: 'course',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    instructor: 'Tahmid "SniperX" Rahman',
    instructorBio: 'National Esports Tournament MVP & Professional Battle Royale Coach.',
    durationMinutes: 240,
    totalLessons: 4,
    level: 'All Levels',
    published: true,
    skills: ['Gyroscope Control', 'Recoil Mastery', 'Esports Rotations', 'Close Range Aim', 'Game Sense'],
    createdAt: '2026-08-09T14:00:00.000Z',
    updatedAt: '2026-08-29T10:00:00.000Z'
  },
  {
    id: 'course-6',
    title: 'Blender 3D Character Modeling & Rigging for Games',
    description: 'Create low-poly and high-poly 3D game assets, UV unwrapping, PBR texturing, and humanoid bone rigging in Blender 4.',
    longDescription: 'Comprehensive 3D asset creation pipeline. Model a complete warrior character from 2D concept to finished 3D mesh ready for Unity and Unreal Engine animation retargeting.',
    thumbnail: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&w=600&q=80',
    category: 'Game Development',
    type: 'course',
    accessType: 'PAID',
    price: 450,
    currency: 'BDT',
    instructor: 'Nazmul Hoda',
    instructorBio: 'Senior 3D Artist with 7 years modeling for indie games and cinematic VFX studios.',
    durationMinutes: 600,
    totalLessons: 5,
    level: 'Intermediate',
    published: true,
    skills: ['Blender 4', '3D Modeling', 'Sculpting', 'UV Unwrapping', 'Substance Texturing', 'Rigging & Weights'],
    createdAt: '2026-08-11T15:00:00.000Z',
    updatedAt: '2026-08-30T14:00:00.000Z'
  },
  {
    id: 'course-7',
    title: 'Mobile Legends Mythic Rank Hero & Macro Strategy Guide',
    description: 'Macro map awareness, jungle rotation timings, draft pick strategy, itemization counters, and lane freezing.',
    longDescription: 'Break out of Epic/Legend into Mythical Glory. Master vision control, lord baiting, split pushing, and adapting your item builds to dominate high-elo ranked matches.',
    thumbnail: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=600&q=80',
    category: 'Online Gaming & Esports',
    type: 'course',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    instructor: 'Farhan "Zephyr" Hossain',
    instructorBio: 'Top 1 Global Hero Specialist and Regional MLBB Tournament Analyst.',
    durationMinutes: 180,
    totalLessons: 3,
    level: 'Intermediate',
    published: true,
    skills: ['Macro Gameplay', 'Draft Strategy', 'Jungle Timings', 'Counter Itemization', 'Teamfight Positioning'],
    createdAt: '2026-08-13T10:00:00.000Z',
    updatedAt: '2026-08-30T16:00:00.000Z'
  },
  {
    id: 'course-8',
    title: 'Shader Graph & Visual VFX for Unity Mobile Games',
    description: 'Craft stunning cartoon water, energy shields, hologram scans, dissolve shaders, and custom particle effects.',
    longDescription: 'Unleash the visual power of Unity Universal Render Pipeline (URP) without writing HLSL code. Create stylized lighting, glowing portals, and explosive special effects optimized for budget mobile devices.',
    thumbnail: 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?auto=format&fit=crop&w=600&q=80',
    category: 'Game Development',
    type: 'course',
    accessType: 'PAID',
    price: 299,
    currency: 'BDT',
    instructor: 'Rashedul Islam',
    instructorBio: 'Lead Game Developer & Technical Artist.',
    durationMinutes: 300,
    totalLessons: 4,
    level: 'Intermediate',
    published: true,
    skills: ['Unity Shader Graph', 'URP Pipeline', 'VFX Graph', 'Visual Polish', 'Mobile Performance'],
    createdAt: '2026-08-15T11:00:00.000Z',
    updatedAt: '2026-08-31T09:00:00.000Z'
  },
  {
    id: 'course-9',
    title: 'Multiplayer Game Networking with C# & Photon Fusion',
    description: 'Build real-time multiplayer mobile games with lag compensation, client prediction, matchmaking, and voice chat.',
    longDescription: 'Understand authoritative server models, state replication, RPCs, tick rates, and handling intermittent mobile 4G/5G connections smoothly.',
    thumbnail: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=600&q=80',
    category: 'Game Development',
    type: 'course',
    accessType: 'PAID',
    price: 499,
    currency: 'BDT',
    instructor: 'Engr. Tanvir Ahmed',
    instructorBio: 'Senior Principal Software Engineer & Cloud Architect.',
    durationMinutes: 480,
    totalLessons: 4,
    level: 'Advanced',
    published: true,
    skills: ['Photon Fusion', 'Multiplayer Networking', 'RPCs', 'Interpolation', 'Lobby Matchmaking'],
    createdAt: '2026-08-17T12:00:00.000Z',
    updatedAt: '2026-08-31T11:00:00.000Z'
  },
  {
    id: 'course-10',
    title: 'Game Audio Design & Dynamic Music with FMOD Studio',
    description: 'Compose adaptive soundtracks, sound effects, gunshots, footsteps, and spatial 3D audio for video games.',
    longDescription: 'Connect FMOD middleware to Unity and Unreal. Learn dynamic parameter triggers, sound pitch randomization, and ambient soundscapes that change with player health and combat intensity.',
    thumbnail: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=600&q=80',
    category: 'Game Development',
    type: 'course',
    accessType: 'PAID',
    price: 249,
    currency: 'BDT',
    instructor: 'Kazi Noman',
    instructorBio: 'Sound Designer & Audio Engineer with credits in international game jams and indie releases.',
    durationMinutes: 280,
    totalLessons: 3,
    level: 'All Levels',
    published: true,
    skills: ['FMOD Studio', 'Interactive Audio', 'Sound Design', 'Spatial 3D Sound', 'Unity Integration'],
    createdAt: '2026-08-19T14:00:00.000Z',
    updatedAt: '2026-08-31T13:00:00.000Z'
  },

  // 11-25: Mobile & Full-Stack Development
  {
    id: 'course-11',
    title: 'Modern Full-Stack Node.js & React Architecture Masterclass',
    description: 'Learn to build, secure, and deploy high-performance web and mobile apps with Express, React 19, JWT, and Cloud Run.',
    longDescription: 'Comprehensive hands-on curriculum taking you from fundamental HTTP primitives to enterprise microservices, token authentication, payment gateway integrations (bKash, Stripe, SSLCommerz), database modeling, and server-side optimization.',
    thumbnail: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&w=600&q=80',
    category: 'Web & Full-Stack',
    type: 'course',
    accessType: 'PAID',
    price: 1200,
    currency: 'BDT',
    instructor: 'Engr. Tanvir Ahmed',
    instructorBio: 'Senior Principal Software Engineer & Cloud Architect with 10+ years scaling full-stack platforms across South Asia.',
    durationMinutes: 480,
    totalLessons: 6,
    level: 'All Levels',
    published: true,
    skills: ['Node.js', 'Express', 'React 19', 'JWT Security', 'Payment Gateways', 'API Design', 'Production Deployment'],
    createdAt: '2026-08-05T09:00:00.000Z',
    updatedAt: '2026-08-27T15:00:00.000Z'
  },
  {
    id: 'course-12',
    title: 'Android Kotlin & Jetpack Compose: Zero to Production',
    description: 'Master modern Android development with Kotlin 2.0, declarative Compose UI, StateFlow, Room DB, and MVVM Clean Architecture.',
    longDescription: 'Build real-world Android apps from scratch. Master coroutines, asynchronous flows, dependency injection with Hilt, Retrofit REST networking, offline-first data caching with Room, and publishing signed APKs/AABs.',
    thumbnail: 'https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?auto=format&fit=crop&w=600&q=80',
    category: 'Android Mastery',
    type: 'course',
    accessType: 'PAID',
    price: 950,
    currency: 'BDT',
    instructor: 'Mahmudul Hasan',
    instructorBio: 'Staff Android Engineer & Google Developer Expert with 12+ production apps on Google Play.',
    durationMinutes: 540,
    totalLessons: 4,
    level: 'Intermediate',
    published: true,
    skills: ['Kotlin 2.0', 'Jetpack Compose', 'MVVM Clean Architecture', 'Hilt DI', 'Room DB', 'Coroutines'],
    createdAt: '2026-08-07T11:00:00.000Z',
    updatedAt: '2026-08-28T10:00:00.000Z'
  },
  {
    id: 'course-13',
    title: 'Flutter 3.x & Dart Multi-Platform Masterclass (Android & iOS)',
    description: 'Build gorgeous native Android and iOS mobile apps from a single Dart codebase with Riverpod and Firebase.',
    longDescription: 'Comprehensive Flutter training: state management with Riverpod 2.0, responsive UI layouts, animations, push notifications, REST APIs, and publishing to Google Play and Apple App Store.',
    thumbnail: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?auto=format&fit=crop&w=600&q=80',
    category: 'Android Mastery',
    type: 'course',
    accessType: 'PAID',
    price: 800,
    currency: 'BDT',
    instructor: 'Shuvo Roy',
    instructorBio: 'Senior Flutter Consultant with cross-platform apps serving over 1M+ active users.',
    durationMinutes: 620,
    totalLessons: 5,
    level: 'All Levels',
    published: true,
    skills: ['Flutter 3.x', 'Dart', 'Riverpod', 'Firebase Auth', 'REST APIs', 'Custom Animations'],
    createdAt: '2026-08-08T14:00:00.000Z',
    updatedAt: '2026-08-29T12:00:00.000Z'
  },
  {
    id: 'course-14',
    title: 'React Native & Expo: High-Speed Mobile App Development',
    description: 'Create lightning-fast iOS & Android apps with React Native, TypeScript, Tailwind (NativeWind), and EAS Build.',
    longDescription: 'Learn React Native in 2026 with Expo Router, gesture handlers, native reanimated 3 physics, offline local SQLite, and instant OTA app updates.',
    thumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=600&q=80',
    category: 'Web & Full-Stack',
    type: 'course',
    accessType: 'PAID',
    price: 750,
    currency: 'BDT',
    instructor: 'Engr. Tanvir Ahmed',
    instructorBio: 'Senior Principal Software Engineer.',
    durationMinutes: 420,
    totalLessons: 4,
    level: 'Intermediate',
    published: true,
    skills: ['React Native', 'Expo Router', 'TypeScript', 'NativeWind', 'Reanimated 3', 'App Store Deploy'],
    createdAt: '2026-08-10T10:00:00.000Z',
    updatedAt: '2026-08-30T10:00:00.000Z'
  },
  {
    id: 'course-15',
    title: 'Python for AI, Machine Learning & Automation Bootcamp',
    description: 'Learn Python programming, NumPy, Pandas data analytics, web scraping, and integrating Gemini & OpenAI models.',
    longDescription: 'From core Python syntax to advanced AI agents. Automate tedious tasks, build web scrapers with BeautifulSoup/Playwright, analyze data, and build intelligent AI chatbots.',
    thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=600&q=80',
    category: 'Developer Tools',
    type: 'course',
    accessType: 'PAID',
    price: 550,
    currency: 'BDT',
    instructor: 'Dr. Shahriar Rahman',
    instructorBio: 'Data Scientist & AI Researcher with publications in computer vision and generative models.',
    durationMinutes: 510,
    totalLessons: 5,
    level: 'All Levels',
    published: true,
    skills: ['Python 3.12', 'Pandas & NumPy', 'Web Scraping', 'Gemini AI API', 'Task Automation', 'FastAPI'],
    createdAt: '2026-08-12T09:00:00.000Z',
    updatedAt: '2026-08-30T13:00:00.000Z'
  },
  {
    id: 'course-16',
    title: 'Next.js 15 & Server Components Full-Stack Architecture',
    description: 'App Router, React Server Components (RSC), Server Actions, Prisma ORM, PostgreSQL, and Vercel edge caching.',
    longDescription: 'Build modern high-traffic web applications with Next.js 15. Master SEO optimization, streaming SSR, auth with Auth.js, optimistic UI updates, and stripe/bKash checkout.',
    thumbnail: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=600&q=80',
    category: 'Web & Full-Stack',
    type: 'course',
    accessType: 'PAID',
    price: 900,
    currency: 'BDT',
    instructor: 'Zubair Al Mahmud',
    instructorBio: 'Lead Full-Stack Architect building modern React & Next.js SaaS platforms.',
    durationMinutes: 460,
    totalLessons: 4,
    level: 'Intermediate',
    published: true,
    skills: ['Next.js 15', 'Server Actions', 'PostgreSQL', 'Prisma ORM', 'Tailwind CSS', 'Auth.js'],
    createdAt: '2026-08-14T11:00:00.000Z',
    updatedAt: '2026-08-30T16:00:00.000Z'
  },
  {
    id: 'course-17',
    title: 'Ethical Hacking & Android App Penetration Testing',
    description: 'Reverse engineer Android APKs, bypass SSL pinning, analyze Smali code, and find vulnerabilities using Frida and Burp Suite.',
    longDescription: 'Learn professional mobile application security auditing. Discover OWASP Mobile Top 10 vulnerabilities, insecure data storage, hardcoded secrets, and patch security flaws.',
    thumbnail: 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?auto=format&fit=crop&w=600&q=80',
    category: 'Security & Networking',
    type: 'course',
    accessType: 'PAID',
    price: 999,
    currency: 'BDT',
    instructor: 'Ashikur Rahman (CEH)',
    instructorBio: 'Certified Ethical Hacker & Offensive Security Researcher.',
    durationMinutes: 480,
    totalLessons: 4,
    level: 'Advanced',
    published: true,
    skills: ['Android Security', 'Frida & Objection', 'Burp Suite Pro', 'Smali Reverse Engineering', 'SSL Pinning Bypass'],
    createdAt: '2026-08-16T13:00:00.000Z',
    updatedAt: '2026-08-31T08:00:00.000Z'
  },
  {
    id: 'course-18',
    title: 'Golang Microservices & High-Concurrency Backend',
    description: 'Build blazing-fast REST and gRPC microservices with Go routines, channels, Docker, and Redis caching.',
    longDescription: 'Master Go for backend engineering. Learn concurrency patterns, PostgreSQL pooling, JWT authentication, Prometheus monitoring, and deploying containers to Kubernetes.',
    thumbnail: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=600&q=80',
    category: 'Developer Tools',
    type: 'course',
    accessType: 'PAID',
    price: 850,
    currency: 'BDT',
    instructor: 'Engr. Tanvir Ahmed',
    instructorBio: 'Senior Principal Software Engineer.',
    durationMinutes: 400,
    totalLessons: 4,
    level: 'Intermediate',
    published: true,
    skills: ['Golang', 'gRPC', 'Goroutines', 'PostgreSQL', 'Docker', 'Redis'],
    createdAt: '2026-08-18T10:00:00.000Z',
    updatedAt: '2026-08-31T10:00:00.000Z'
  },
  {
    id: 'course-19',
    title: 'Docker, CI/CD & Cloud DevOps with GitHub Actions',
    description: 'Automate build testing, Docker image packaging, and zero-downtime deployment to Google Cloud and VPS servers.',
    longDescription: 'Practical DevOps for developers. Set up Nginx reverse proxy with automated Let\'s Encrypt SSL, multi-stage Dockerfiles, GitHub Action pipelines, and Linux server hardening.',
    thumbnail: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=600&q=80',
    category: 'Developer Tools',
    type: 'course',
    accessType: 'PAID',
    price: 600,
    currency: 'BDT',
    instructor: 'Kamrul Hasan',
    instructorBio: 'DevOps Specialist & Site Reliability Engineer.',
    durationMinutes: 340,
    totalLessons: 3,
    level: 'All Levels',
    published: true,
    skills: ['Docker', 'GitHub Actions', 'Nginx', 'SSL Automation', 'Linux Sysadmin', 'CI/CD Pipelines'],
    createdAt: '2026-08-20T12:00:00.000Z',
    updatedAt: '2026-08-31T12:00:00.000Z'
  },
  {
    id: 'course-20',
    title: 'Bangladesh Payment Gateway Integration Masterclass',
    description: 'End-to-end integration for bKash Tokenized Checkout, Nagad, Rocket, SSLCommerz, and Stripe webhooks in Node.js & PHP.',
    longDescription: 'Stop failing payment verification audits. Learn token grant routines, IPN webhooks, signature verification, automatic transaction reconciliation, and refund APIs.',
    thumbnail: 'https://images.unsplash.com/photo-1556742049-0a67e557224f?auto=format&fit=crop&w=600&q=80',
    category: 'Web & Full-Stack',
    type: 'course',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    instructor: 'Engr. Tanvir Ahmed',
    instructorBio: 'Senior Principal Software Engineer.',
    durationMinutes: 300,
    totalLessons: 4,
    level: 'All Levels',
    published: true,
    skills: ['bKash API', 'Nagad API', 'SSLCommerz', 'Webhook Security', 'Payment Audits', 'Idempotency'],
    createdAt: '2026-08-22T08:00:00.000Z',
    updatedAt: '2026-08-31T14:00:00.000Z'
  },

  // 21-35: Creative, Video Editing, UI/UX & Digital Media
  {
    id: 'course-21',
    title: 'CapCut & Premiere Pro Mobile Video Editing Masterclass',
    description: 'Create viral TikToks, YouTube Shorts, and Reels with cinematic color grading, sound design, and trend effects.',
    longDescription: 'Step-by-step video editing workflow for creators. Master fast-paced pacing, sound effects (whooshes, risers, impacts), text animations, auto captions, and 4K export presets.',
    thumbnail: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=600&q=80',
    category: 'Media, Video & Audio',
    type: 'course',
    accessType: 'PAID',
    price: 350,
    currency: 'BDT',
    instructor: 'Tanvir "VFX" Shawon',
    instructorBio: 'Content Creator with 500K+ followers and professional commercial video editor.',
    durationMinutes: 320,
    totalLessons: 4,
    level: 'Beginner',
    published: true,
    skills: ['CapCut Pro', 'Color Grading', 'Sound Design', 'Viral Hook Editing', 'Auto Captions', '4K Rendering'],
    createdAt: '2026-08-02T10:00:00.000Z',
    updatedAt: '2026-08-26T14:00:00.000Z'
  },
  {
    id: 'course-22',
    title: 'Alight Motion & After Effects Motion Graphics Masterclass',
    description: 'Learn typography kinetic animations, logo reveals, velocity AMV edits, and XML preset creation on mobile & PC.',
    longDescription: 'From graph curves to complex 3D camera sweeps. Master easing transitions, motion blur, displacement maps, glow shaders, and creating shareable preset packages.',
    thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=600&q=80',
    category: 'Media, Video & Audio',
    type: 'course',
    accessType: 'PAID',
    price: 400,
    currency: 'BDT',
    instructor: 'Rimon Ahmed',
    instructorBio: 'Motion Graphics Animator & Visual Effects Designer.',
    durationMinutes: 380,
    totalLessons: 4,
    level: 'Intermediate',
    published: true,
    skills: ['Alight Motion', 'Velocity Editing', 'Kinetic Typography', 'XML Presets', 'Graph Curves'],
    createdAt: '2026-08-04T12:00:00.000Z',
    updatedAt: '2026-08-27T16:00:00.000Z'
  },
  {
    id: 'course-23',
    title: 'UI/UX Design with Figma 2026: Mobile App & Web Mastery',
    description: 'Design beautiful, accessible interfaces with Figma Auto Layout 5.0, variables, design systems, and prototypes.',
    longDescription: 'Complete product design training. Conduct user research, build wireframes, apply typography & color theory, design responsive components with Auto Layout, and create interactive micro-animations.',
    thumbnail: 'https://images.unsplash.com/photo-1581291518857-4e27b48ff24e?auto=format&fit=crop&w=600&q=80',
    category: 'Productivity & Utilities',
    type: 'course',
    accessType: 'PAID',
    price: 650,
    currency: 'BDT',
    instructor: 'Farzana Yesmin',
    instructorBio: 'Senior Product Designer at leading tech startup with experience in mobile fintech and SaaS apps.',
    durationMinutes: 440,
    totalLessons: 4,
    level: 'All Levels',
    published: true,
    skills: ['Figma 2026', 'Auto Layout', 'Design Systems', 'Micro-interactions', 'Prototyping', 'UX Research'],
    createdAt: '2026-08-06T15:00:00.000Z',
    updatedAt: '2026-08-28T11:00:00.000Z'
  },
  {
    id: 'course-24',
    title: 'YouTube Thumbnail Design with PixelLab & Photoshop',
    description: 'High-CTR YouTube thumbnail secret formula: facial expression cutouts, glow highlights, 3D text, and color contrast.',
    longDescription: 'Discover why top YouTubers get millions of clicks. Learn lighting brushes, background blur depth, bold typography hierarchy, and testing CTR thumbnails.',
    thumbnail: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&w=600&q=80',
    category: 'Media, Video & Audio',
    type: 'course',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    instructor: 'Mehedi Hasan',
    instructorBio: 'Graphic Designer for top creators with over 100M+ impressions generated.',
    durationMinutes: 180,
    totalLessons: 3,
    level: 'Beginner',
    published: true,
    skills: ['Thumbnail Design', 'PixelLab Pro', 'Photoshop', 'Color Psychology', 'CTR Optimization'],
    createdAt: '2026-08-08T09:00:00.000Z',
    updatedAt: '2026-08-29T14:00:00.000Z'
  },
  {
    id: 'course-25',
    title: 'Audio Recording & Podcast Mastering with Audacity & FL Studio',
    description: 'Remove microphone background noise, equalize vocals, compress dynamic range, and master broadcast-quality audio.',
    longDescription: 'Turn budget smartphone or USB mic recordings into studio-quality audio. Master noise gates, de-essers, parametric equalizers, warm reverb, and loudness normalization standards.',
    thumbnail: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=600&q=80',
    category: 'Media, Video & Audio',
    type: 'course',
    accessType: 'PAID',
    price: 250,
    currency: 'BDT',
    instructor: 'Kazi Noman',
    instructorBio: 'Audio Engineer & Sound Producer.',
    durationMinutes: 220,
    totalLessons: 3,
    level: 'Beginner',
    published: true,
    skills: ['Vocal Cleaning', 'Audacity', 'Equalization', 'Audio Compression', 'Loudness Mastering'],
    createdAt: '2026-08-10T14:00:00.000Z',
    updatedAt: '2026-08-30T15:00:00.000Z'
  },

  // 36-50: Digital Business, SEO, Freelancing & Growth
  {
    id: 'course-26',
    title: 'YouTube Channel Growth & Monetization Blueprint 2026',
    description: 'Find profitable niches, optimize titles and tags for YouTube search, increase watch time, and scale revenue.',
    longDescription: 'Proven system for starting and growing a monetized YouTube channel. Learn script writing hooks, audience retention graphs, copyright safe music, and affiliate marketing.',
    thumbnail: 'https://images.unsplash.com/photo-1614680376593-902f749f7ffc?auto=format&fit=crop&w=600&q=80',
    category: 'Productivity & Utilities',
    type: 'course',
    accessType: 'PAID',
    price: 499,
    currency: 'BDT',
    instructor: 'Tanvir Shawon',
    instructorBio: 'Full-time Creator with Silver Play Button.',
    durationMinutes: 360,
    totalLessons: 4,
    level: 'All Levels',
    published: true,
    skills: ['YouTube SEO', 'Audience Retention', 'Monetization', 'Content Strategy', 'Video Scripting'],
    createdAt: '2026-08-12T11:00:00.000Z',
    updatedAt: '2026-08-30T17:00:00.000Z'
  },
  {
    id: 'course-27',
    title: 'Facebook Ads & Meta Pixel Marketing Masterclass',
    description: 'Run profitable Facebook & Instagram ad campaigns for e-commerce, leads, custom audiences, and A/B testing.',
    longDescription: 'Stop wasting ad spend on boosted posts. Master Meta Ads Manager, target local Bangladesh buyer behaviors, set up Conversion API, and scale winning ad creatives.',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80',
    category: 'Productivity & Utilities',
    type: 'course',
    accessType: 'PAID',
    price: 599,
    currency: 'BDT',
    instructor: 'Sajid Karim',
    instructorBio: 'Performance Marketer managing $500k+ annual ad budgets for e-commerce brands.',
    durationMinutes: 400,
    totalLessons: 4,
    level: 'Intermediate',
    published: true,
    skills: ['Meta Ads Manager', 'Conversion API', 'Audience Retargeting', 'Copywriting', 'ROAS Optimization'],
    createdAt: '2026-08-14T13:00:00.000Z',
    updatedAt: '2026-08-31T09:00:00.000Z'
  },
  {
    id: 'course-28',
    title: 'Fiverr & Upwork Freelancing Success Bootcamp',
    description: 'Create high-converting gig listings, write winning proposal cover letters, handle international clients, and get 5-star reviews.',
    longDescription: 'Break into global freelancing. Learn client communication etiquette, project pricing strategies, avoiding chargeback disputes, and withdrawing earnings to local banks.',
    thumbnail: 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?auto=format&fit=crop&w=600&q=80',
    category: 'Productivity & Utilities',
    type: 'course',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    instructor: 'Anisur Rahman',
    instructorBio: 'Top Rated Plus Freelancer with $100k+ in earned revenue on Upwork.',
    durationMinutes: 280,
    totalLessons: 3,
    level: 'Beginner',
    published: true,
    skills: ['Fiverr SEO', 'Upwork Proposals', 'Client Management', 'International Banking', 'Pricing Strategy'],
    createdAt: '2026-08-16T08:00:00.000Z',
    updatedAt: '2026-08-31T11:00:00.000Z'
  },
  {
    id: 'course-29',
    title: 'SEO Mastery: Rank #1 on Google in 2026',
    description: 'Keyword research, on-page optimization, technical SEO audits, high-authority backlink building, and AI content ranking.',
    longDescription: 'Comprehensive Search Engine Optimization training for websites and blogs. Master Google search algorithms, Core Web Vitals speed optimization, and schema markup.',
    thumbnail: 'https://images.unsplash.com/photo-1432888622747-4eb9a8f2c293?auto=format&fit=crop&w=600&q=80',
    category: 'Web & Full-Stack',
    type: 'course',
    accessType: 'PAID',
    price: 499,
    currency: 'BDT',
    instructor: 'Tariqul Islam',
    instructorBio: 'Organic Growth Consultant & SEO Strategist.',
    durationMinutes: 350,
    totalLessons: 4,
    level: 'All Levels',
    published: true,
    skills: ['Technical SEO', 'Keyword Research', 'Backlink Building', 'Core Web Vitals', 'Search Console'],
    createdAt: '2026-08-18T09:00:00.000Z',
    updatedAt: '2026-08-31T13:00:00.000Z'
  },
  {
    id: 'course-30',
    title: 'Canva Pro for Freelancers: Social Media Design Business',
    description: 'Start a design agency with Canva: create branding kits, restaurant menus, product catalogs, and animated social posts.',
    longDescription: 'Turn Canva into a full-time freelancing income stream. Learn typography pairing, composition rules, batch creating 30 days of posts in 1 hour, and exporting print-ready files.',
    thumbnail: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&w=600&q=80',
    category: 'Productivity & Utilities',
    type: 'course',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    instructor: 'Nasrin Sultana',
    instructorBio: 'Digital Creator & Canva Certified Designer.',
    durationMinutes: 210,
    totalLessons: 3,
    level: 'Beginner',
    published: true,
    skills: ['Canva Pro', 'Brand Kits', 'Social Media Graphics', 'Print Design', 'Client Presentation'],
    createdAt: '2026-08-20T11:00:00.000Z',
    updatedAt: '2026-08-31T15:00:00.000Z'
  },
  {
    id: 'course-31',
    title: 'Android App Reverse Engineering & Security Hardening',
    description: 'Protect your APKs from cracking, patching, and piracy using R8, ProGuard rules, integrity checks, and Play Integrity API.',
    longDescription: 'Defend your mobile intellectual property against unauthorized modification. Learn runtime tampering detection, root detection, and API request HMAC signing.',
    thumbnail: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=600&q=80',
    category: 'Android Mastery',
    type: 'course',
    accessType: 'PAID',
    price: 699,
    currency: 'BDT',
    instructor: 'Mahmudul Hasan',
    instructorBio: 'Staff Android Engineer.',
    durationMinutes: 320,
    totalLessons: 3,
    level: 'Advanced',
    published: true,
    skills: ['ProGuard & R8', 'Play Integrity API', 'Anti-Tamper', 'Root Detection', 'APK Obfuscation'],
    createdAt: '2026-08-01T14:00:00.000Z',
    updatedAt: '2026-08-25T11:00:00.000Z'
  },
  {
    id: 'course-32',
    title: 'C++ for Game Development & High-Performance Graphics',
    description: 'Master C++20 pointers, memory management, data structures, multithreading, and OpenGL graphics programming.',
    longDescription: 'The gold standard for AAA game development. Understand stack vs heap allocation, smart pointers, SIMD vectorization, and building a 3D software rasterizer.',
    thumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=600&q=80',
    category: 'Game Development',
    type: 'course',
    accessType: 'PAID',
    price: 799,
    currency: 'BDT',
    instructor: 'Arif Chowdhury',
    instructorBio: 'Senior Technical Designer & Systems Programmer.',
    durationMinutes: 500,
    totalLessons: 4,
    level: 'Advanced',
    published: true,
    skills: ['C++20', 'Memory Management', 'Data Structures', 'OpenGL', 'Multithreading'],
    createdAt: '2026-08-03T16:00:00.000Z',
    updatedAt: '2026-08-26T17:00:00.000Z'
  },
  {
    id: 'course-33',
    title: 'Prompt Engineering & Building AI Apps with Gemini 2.0',
    description: 'Build production AI applications with Gemini Flash, multimodal image analysis, function calling, and structured outputs.',
    longDescription: 'Learn cutting-edge generative AI engineering. Build document analyzers, automated coding assistants, live speech apps, and custom agentic workflows using the official SDK.',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
    category: 'Developer Tools',
    type: 'course',
    accessType: 'PAID',
    price: 599,
    currency: 'BDT',
    instructor: 'Engr. Tanvir Ahmed',
    instructorBio: 'Senior Principal Software Engineer & AI Studio Specialist.',
    durationMinutes: 360,
    totalLessons: 4,
    level: 'All Levels',
    published: true,
    skills: ['Gemini 2.0 SDK', 'Function Calling', 'Structured JSON Output', 'Multimodal AI', 'Agent Workflows'],
    createdAt: '2026-08-05T12:00:00.000Z',
    updatedAt: '2026-08-27T10:00:00.000Z'
  },
  {
    id: 'course-34',
    title: 'Kotlin Coroutines, Flow & Concurrency Deep Dive',
    description: 'Master asynchronous programming in Kotlin: Dispatchers, exception handling, Channels, SharedFlow, and StateFlow.',
    longDescription: 'Stop race conditions and memory leaks. Learn structured concurrency, debounce search queries, combine multiple network streams, and unit test asynchronous flows.',
    thumbnail: 'https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?auto=format&fit=crop&w=600&q=80',
    category: 'Android Mastery',
    type: 'course',
    accessType: 'PAID',
    price: 450,
    currency: 'BDT',
    instructor: 'Mahmudul Hasan',
    instructorBio: 'Staff Android Engineer.',
    durationMinutes: 280,
    totalLessons: 3,
    level: 'Intermediate',
    published: true,
    skills: ['Kotlin Coroutines', 'StateFlow', 'Channels', 'Structured Concurrency', 'Async Unit Testing'],
    createdAt: '2026-08-07T08:00:00.000Z',
    updatedAt: '2026-08-28T09:00:00.000Z'
  },
  {
    id: 'course-35',
    title: 'PostgreSQL & Database Optimization for High Load',
    description: 'Master relational schema design, indexing strategies, query execution plans, connection pooling, and replication.',
    longDescription: 'Scale your relational databases to handle millions of queries per day. Learn B-tree vs GIN indexes, partitioning large tables, EXPLAIN ANALYZE tuning, and PgBouncer.',
    thumbnail: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=600&q=80',
    category: 'Web & Full-Stack',
    type: 'course',
    accessType: 'PAID',
    price: 550,
    currency: 'BDT',
    instructor: 'Zubair Al Mahmud',
    instructorBio: 'Lead Full-Stack Architect.',
    durationMinutes: 340,
    totalLessons: 3,
    level: 'Intermediate',
    published: true,
    skills: ['PostgreSQL', 'Query Optimization', 'Indexing Strategies', 'Table Partitioning', 'PgBouncer'],
    createdAt: '2026-08-09T13:00:00.000Z',
    updatedAt: '2026-08-29T13:00:00.000Z'
  },
  {
    id: 'course-36',
    title: 'HTML, Modern CSS & Tailwind CSS Zero to Hero',
    description: 'Build responsive, pixel-perfect, mobile-friendly landing pages and dashboards with modern semantic HTML & Tailwind.',
    longDescription: 'The essential foundation for modern web design. Master flexbox, CSS grid, media queries, dark mode switching, animations, and container queries without writing complex vanilla CSS.',
    thumbnail: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=600&q=80',
    category: 'Web & Full-Stack',
    type: 'course',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    instructor: 'Saiful Alam',
    instructorBio: 'Frontend Engineer & UI Specialist.',
    durationMinutes: 300,
    totalLessons: 3,
    level: 'Beginner',
    published: true,
    skills: ['HTML5', 'Tailwind CSS', 'CSS Grid & Flexbox', 'Responsive Design', 'Dark Mode'],
    createdAt: '2026-08-11T10:00:00.000Z',
    updatedAt: '2026-08-30T11:00:00.000Z'
  },
  {
    id: 'course-37',
    title: 'TypeScript 5.8 Complete Developer Bootcamp',
    description: 'Master types, interfaces, generics, utility types, type guards, discriminative unions, and TSConfig optimization.',
    longDescription: 'Write robust, bug-free JavaScript at scale. Learn how TypeScript compiles, integrate with React and Express, handle complex asynchronous payloads, and write custom type definitions.',
    thumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=600&q=80',
    category: 'Developer Tools',
    type: 'course',
    accessType: 'PAID',
    price: 399,
    currency: 'BDT',
    instructor: 'Engr. Tanvir Ahmed',
    instructorBio: 'Senior Principal Software Engineer.',
    durationMinutes: 310,
    totalLessons: 3,
    level: 'All Levels',
    published: true,
    skills: ['TypeScript 5.8', 'Generics', 'Type Narrowing', 'Advanced Interfaces', 'Strict Typing'],
    createdAt: '2026-08-13T15:00:00.000Z',
    updatedAt: '2026-08-30T14:00:00.000Z'
  },
  {
    id: 'course-38',
    title: 'Mobile Game Marketing, ASO & Monetization Strategy',
    description: 'App Store Optimization (ASO), keyword research for Google Play, reward video ad placement, and in-app purchases.',
    longDescription: 'Get organic downloads for your games and apps. Learn icon A/B testing, screenshot conversion psychology, Google Play Console metrics, and integrating AdMob/Unity Ads.',
    thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=600&q=80',
    category: 'Online Gaming & Esports',
    type: 'course',
    accessType: 'PAID',
    price: 450,
    currency: 'BDT',
    instructor: 'Rashedul Islam',
    instructorBio: 'Lead Game Developer & ASO Specialist.',
    durationMinutes: 260,
    totalLessons: 3,
    level: 'All Levels',
    published: true,
    skills: ['ASO Strategy', 'Google Play Console', 'AdMob Integration', 'In-App Purchases', 'Organic Growth'],
    createdAt: '2026-08-15T08:00:00.000Z',
    updatedAt: '2026-08-31T08:00:00.000Z'
  },
  {
    id: 'course-39',
    title: 'Linux Command Line, Bash Scripting & System Administration',
    description: 'Master terminal commands, file permissions, SSH keys, cron jobs, process management, and automated shell scripts.',
    longDescription: 'The definitive Linux handbook for developers and sysadmins. Learn grep, awk, sed, systemd service units, firewall setup with ufw, and automating server backups.',
    thumbnail: 'https://images.unsplash.com/photo-1629654297299-c8506221ca97?auto=format&fit=crop&w=600&q=80',
    category: 'Developer Tools',
    type: 'course',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    instructor: 'Kamrul Hasan',
    instructorBio: 'DevOps Specialist.',
    durationMinutes: 240,
    totalLessons: 3,
    level: 'Beginner',
    published: true,
    skills: ['Linux CLI', 'Bash Scripting', 'SSH Management', 'Cron Automation', 'Systemd Services'],
    createdAt: '2026-08-17T14:00:00.000Z',
    updatedAt: '2026-08-31T10:00:00.000Z'
  },
  {
    id: 'course-40',
    title: 'WordPress & WooCommerce Speed & Security Optimization',
    description: 'Speed up slow WordPress sites to under 1-second load times, configure Redis object caching, Cloudflare, and firewall protection.',
    longDescription: 'Turn slow WooCommerce stores into high-speed sales machines. Optimize images with WebP, eliminate render-blocking CSS/JS, harden against brute force attacks, and set up daily cloud backups.',
    thumbnail: 'https://images.unsplash.com/photo-1432888622747-4eb9a8f2c293?auto=format&fit=crop&w=600&q=80',
    category: 'Productivity & Utilities',
    type: 'course',
    accessType: 'PAID',
    price: 350,
    currency: 'BDT',
    instructor: 'Tariqul Islam',
    instructorBio: 'Organic Growth Consultant & Web Architect.',
    durationMinutes: 270,
    totalLessons: 3,
    level: 'All Levels',
    published: true,
    skills: ['WordPress Speed', 'WooCommerce', 'Redis Cache', 'Cloudflare CDN', 'Site Hardening'],
    createdAt: '2026-08-19T09:00:00.000Z',
    updatedAt: '2026-08-31T12:00:00.000Z'
  },
  {
    id: 'course-41',
    title: 'Web Security, OWASP Top 10 & API Hardening',
    description: 'Learn SQL injection, XSS prevention, CSRF tokens, rate limiting, secure HTTP headers, and OAuth 2.0 authentication.',
    longDescription: 'Secure your Node.js, Python, and PHP applications against real-world hackers. Understand attack vectors, penetration defense, helmet middleware, and secure cookie storage.',
    thumbnail: 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?auto=format&fit=crop&w=600&q=80',
    category: 'Security & Networking',
    type: 'course',
    accessType: 'PAID',
    price: 650,
    currency: 'BDT',
    instructor: 'Ashikur Rahman (CEH)',
    instructorBio: 'Certified Ethical Hacker.',
    durationMinutes: 360,
    totalLessons: 3,
    level: 'Intermediate',
    published: true,
    skills: ['OWASP Top 10', 'API Hardening', 'XSS & CSRF Defense', 'Rate Limiting', 'OAuth 2.0'],
    createdAt: '2026-08-02T13:00:00.000Z',
    updatedAt: '2026-08-26T10:00:00.000Z'
  },
  {
    id: 'course-42',
    title: 'Game Level Design & Environmental Storytelling',
    description: 'Design captivating game maps, pacing, landmark navigation, lighting mood, and player psychological direction.',
    longDescription: 'Learn how great games guide player movement without overt markers. Master leading lines, visual contrast, reward placements, and spatial tension across single-player and multiplayer arenas.',
    thumbnail: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=600&q=80',
    category: 'Game Development',
    type: 'course',
    accessType: 'PAID',
    price: 399,
    currency: 'BDT',
    instructor: 'Arif Chowdhury',
    instructorBio: 'Senior Technical Designer.',
    durationMinutes: 290,
    totalLessons: 3,
    level: 'All Levels',
    published: true,
    skills: ['Level Design', 'Environmental Storytelling', 'Map Flow & Pacing', 'Lighting Composition', 'Player Direction'],
    createdAt: '2026-08-04T16:00:00.000Z',
    updatedAt: '2026-08-27T12:00:00.000Z'
  },
  {
    id: 'course-43',
    title: 'FastAPI & Modern Async Python Microservices',
    description: 'Build high-speed asynchronous REST APIs with Python 3.12, Pydantic data validation, SQLAlchemy, and automated Swagger docs.',
    longDescription: 'The modern Python backend standard. Build async database queries, background worker tasks with Celery/Redis, JWT auth, and automated test suites with pytest.',
    thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=600&q=80',
    category: 'Developer Tools',
    type: 'course',
    accessType: 'PAID',
    price: 499,
    currency: 'BDT',
    instructor: 'Dr. Shahriar Rahman',
    instructorBio: 'Data Scientist & AI Researcher.',
    durationMinutes: 320,
    totalLessons: 3,
    level: 'Intermediate',
    published: true,
    skills: ['FastAPI', 'Pydantic v2', 'Async Python', 'SQLAlchemy 2.0', 'Swagger Documentation'],
    createdAt: '2026-08-06T11:00:00.000Z',
    updatedAt: '2026-08-28T14:00:00.000Z'
  },
  {
    id: 'course-44',
    title: 'GraphQL API Design with Apollo Server & Client',
    description: 'Replace over-fetching REST endpoints with dynamic GraphQL queries, mutations, subscriptions, and schema stitching.',
    longDescription: 'Design scalable GraphQL APIs with Node.js and TypeScript. Learn schema design, dataloaders for N+1 prevention, client-side caching with Apollo Client, and real-time WebSocket subscriptions.',
    thumbnail: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&w=600&q=80',
    category: 'Web & Full-Stack',
    type: 'course',
    accessType: 'PAID',
    price: 450,
    currency: 'BDT',
    instructor: 'Zubair Al Mahmud',
    instructorBio: 'Lead Full-Stack Architect.',
    durationMinutes: 280,
    totalLessons: 3,
    level: 'Intermediate',
    published: true,
    skills: ['GraphQL', 'Apollo Server', 'Apollo Client', 'DataLoaders', 'Realtime Subscriptions'],
    createdAt: '2026-08-08T15:00:00.000Z',
    updatedAt: '2026-08-29T16:00:00.000Z'
  },
  {
    id: 'course-45',
    title: 'Snapseed & Lightroom Mobile Master Photo Retouching',
    description: 'Color grading, split toning, selective mask adjustments, portrait skin smoothing, and creating custom DNG presets.',
    longDescription: 'Transform raw smartphone photos into magazine-worthy editorial portraits and landscape photos using Lightroom Mobile and Snapseed on Android.',
    thumbnail: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?auto=format&fit=crop&w=600&q=80',
    category: 'Media, Video & Audio',
    type: 'course',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    instructor: 'Mehedi Hasan',
    instructorBio: 'Photographer & Graphic Designer.',
    durationMinutes: 190,
    totalLessons: 3,
    level: 'Beginner',
    published: true,
    skills: ['Lightroom Mobile', 'Color Grading', 'DNG Presets', 'Selective Masking', 'RAW Processing'],
    createdAt: '2026-08-10T12:00:00.000Z',
    updatedAt: '2026-08-30T12:00:00.000Z'
  },
  {
    id: 'course-46',
    title: 'Game Physics & Particle Systems Deep Dive',
    description: 'Simulate realistic explosions, ragdolls, vehicle suspension, fluid dynamics, and destruction physics in Unity.',
    longDescription: 'Take your game visual feedback to the next level. Learn custom physics joints, raycast wheel suspension, compute shaders for particle swarms, and memory pooling for zero garbage collection.',
    thumbnail: 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?auto=format&fit=crop&w=600&q=80',
    category: 'Game Development',
    type: 'course',
    accessType: 'PAID',
    price: 399,
    currency: 'BDT',
    instructor: 'Rashedul Islam',
    instructorBio: 'Lead Game Developer & Technical Artist.',
    durationMinutes: 270,
    totalLessons: 3,
    level: 'Intermediate',
    published: true,
    skills: ['Game Physics', 'Particle Systems', 'Vehicle Suspension', 'Ragdoll Dynamics', 'Memory Pooling'],
    createdAt: '2026-08-12T16:00:00.000Z',
    updatedAt: '2026-08-30T18:00:00.000Z'
  },
  {
    id: 'course-47',
    title: 'E-commerce Dropshipping & Local Delivery in Bangladesh',
    description: 'Set up profitable e-commerce operations, source trending products, integrate courier APIs (Steadfast, Pathao, RedX), and prevent returns.',
    longDescription: 'The ultimate guide to running an online business in Bangladesh. Master Cash on Delivery (COD) workflows, courier API automation, fraud verification, and customer retention strategies.',
    thumbnail: 'https://images.unsplash.com/photo-1556742049-0a67e557224f?auto=format&fit=crop&w=600&q=80',
    category: 'Productivity & Utilities',
    type: 'course',
    accessType: 'PAID',
    price: 499,
    currency: 'BDT',
    instructor: 'Sajid Karim',
    instructorBio: 'E-commerce Operator & Performance Marketer.',
    durationMinutes: 310,
    totalLessons: 3,
    level: 'All Levels',
    published: true,
    skills: ['Courier APIs', 'Cash on Delivery', 'Fraud Prevention', 'Order Fulfillment', 'Customer Support'],
    createdAt: '2026-08-14T09:00:00.000Z',
    updatedAt: '2026-08-31T09:00:00.000Z'
  },
  {
    id: 'course-48',
    title: 'Redis Caching & Real-Time Pub/Sub Architecture',
    description: 'In-memory caching patterns, session stores, rate limiters, distributed locks with Redlock, and Pub/Sub chat messaging.',
    longDescription: 'Prevent database overload. Learn cache-aside pattern, cache invalidation strategies, Redis geospatial queries, sorted sets for game leaderboards, and streaming pipelines.',
    thumbnail: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=600&q=80',
    category: 'Web & Full-Stack',
    type: 'course',
    accessType: 'PAID',
    price: 399,
    currency: 'BDT',
    instructor: 'Engr. Tanvir Ahmed',
    instructorBio: 'Senior Principal Software Engineer.',
    durationMinutes: 250,
    totalLessons: 3,
    level: 'Intermediate',
    published: true,
    skills: ['Redis', 'Caching Patterns', 'Pub/Sub', 'Game Leaderboards', 'Distributed Locks'],
    createdAt: '2026-08-16T11:00:00.000Z',
    updatedAt: '2026-08-31T11:00:00.000Z'
  },
  {
    id: 'course-49',
    title: '2D Pixel Art & Sprite Animation for Indie Games',
    description: 'Create retro game characters, walk cycles, attack frames, tilesets, and UI icons using Aseprite and Pixel Studio.',
    longDescription: 'Learn pixel art fundamentals: color palettes, shading, anti-aliasing techniques, frame-by-frame character walk cycles, and exporting sprite sheets ready for game engines.',
    thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=600&q=80',
    category: 'Game Development',
    type: 'course',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    instructor: 'Saiful Alam',
    instructorBio: 'Indie Game Creator & Pixel Artist.',
    durationMinutes: 200,
    totalLessons: 3,
    level: 'Beginner',
    published: true,
    skills: ['Pixel Art', 'Aseprite', 'Sprite Animation', 'Tilesets', 'Color Palettes'],
    createdAt: '2026-08-18T15:00:00.000Z',
    updatedAt: '2026-08-31T13:00:00.000Z'
  },
  {
    id: 'course-50',
    title: 'Mastering Android Architecture: Modular Clean Architecture',
    description: 'Multi-module project setup, dynamic feature modules, convention plugins, and enterprise Android codebase architecture.',
    longDescription: 'Learn how top tech companies structure large-scale Android codebases. Master Gradle version catalogs, internal feature modules, core design systems, and rapid build caching.',
    thumbnail: 'https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?auto=format&fit=crop&w=600&q=80',
    category: 'Android Mastery',
    type: 'course',
    accessType: 'PAID',
    price: 899,
    currency: 'BDT',
    instructor: 'Mahmudul Hasan',
    instructorBio: 'Staff Android Engineer & Google Developer Expert.',
    durationMinutes: 420,
    totalLessons: 4,
    level: 'Advanced',
    published: true,
    skills: ['Modular Android', 'Gradle Version Catalogs', 'Clean Architecture', 'Dynamic Feature Delivery', 'Enterprise Scale'],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-31T15:00:00.000Z'
  }
];
