import { ApkItem } from '../db';

export const seedApks: ApkItem[] = [
  // 1-10: Popular Online Gaming & Esports Tools / Games
  {
    id: 'apk-1',
    title: 'PUBG Mobile GFX Tool & 120 FPS Optimizer',
    description: 'Unlock 90 FPS / 120 FPS, ultra HDR graphics, iPad view, and zero-lag rendering for online battle royale.',
    detailedNotes: 'Clean GPU acceleration and memory garbage collection suite tailored for Snapdragon and MediaTek Dimensity chipsets. Includes anti-heating mode and customized crosshair overlay.',
    thumbnail: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/pubg-gfx-optimizer-v4.8.apk',
    fileName: 'pubg-gfx-optimizer-v4.8.apk',
    fileSize: '14.2 MB',
    version: 'v4.8.2',
    category: 'Online Gaming & Esports',
    type: 'apk',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    downloadsCount: 14280,
    published: true,
    developer: 'ProGamer Studio',
    packageId: 'com.progamer.pubggfxpro',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: 'a1b2c3d4e5f60718293a4b5c6d7e8f90123456789abcdef0123456789abcdef1',
    changelog: ['Added 120FPS support for Android 15', 'Resolved Android 14 Scoped Storage access permissions', 'New dynamic crosshair styling kit'],
    createdAt: '2026-08-10T10:00:00.000Z',
    updatedAt: '2026-08-25T14:30:00.000Z'
  },
  {
    id: 'apk-2',
    title: 'Free Fire MAX Headshot Sensei & DPI Booster',
    description: 'Precision sensitivity calculator, custom HUD generator, and red-dot touch response optimizer.',
    detailedNotes: 'Calculates optimal DPI settings for over 400 smartphone models. Features custom touch acceleration and drag-headshot practice canvas.',
    thumbnail: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/freefire-sensei-v3.2.apk',
    fileName: 'freefire-sensei-v3.2.apk',
    fileSize: '18.9 MB',
    version: 'v3.2.0',
    category: 'Online Gaming & Esports',
    type: 'apk',
    accessType: 'PAID',
    price: 49,
    currency: 'BDT',
    downloadsCount: 8940,
    published: true,
    developer: 'Apex Esports Devs',
    packageId: 'com.apex.ffsensei',
    minAndroidVersion: 'Android 7.0+',
    sha256Checksum: 'b2c3d4e5f60718293a4b5c6d7e8f90123456789abcdef0123456789abcdef2',
    changelog: ['Updated sensitivity presets for OB45 update', 'New floating mini sensitivity widget'],
    createdAt: '2026-08-12T11:00:00.000Z',
    updatedAt: '2026-08-26T12:00:00.000Z'
  },
  {
    id: 'apk-3',
    title: 'Mobile Legends Bang Bang Deck & Counter Pick Pro',
    description: 'Real-time hero win rates, counter pick calculator, emblem builder, and equipment build simulator.',
    detailedNotes: 'Synchronizes with global Mythic rank meta data. Offers counter hero strategies, item counter recommendations, and spell timings.',
    thumbnail: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/mlbb-counterpick-v2.9.apk',
    fileName: 'mlbb-counterpick-v2.9.apk',
    fileSize: '22.5 MB',
    version: 'v2.9.1',
    category: 'Online Gaming & Esports',
    type: 'apk',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    downloadsCount: 6510,
    published: true,
    developer: 'Mythic Labs',
    packageId: 'com.mythic.mlbbcounter',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: 'c3d4e5f60718293a4b5c6d7e8f90123456789abcdef0123456789abcdef3',
    changelog: ['Added new assassin and mage counter matrix', 'Emblem talent points calculator v3'],
    createdAt: '2026-08-14T09:00:00.000Z',
    updatedAt: '2026-08-27T08:00:00.000Z'
  },
  {
    id: 'apk-4',
    title: 'Minecraft Bedrock Master Shader & Addon Hub',
    description: 'One-click installer for 4K ray-tracing shaders, texture packs, realistic water, and survival mod packs.',
    detailedNotes: 'Directly injects .mcpack and .mcaddon files into Minecraft Bedrock edition with automatic backup and resource pack switcher.',
    thumbnail: 'https://images.unsplash.com/photo-1627856013091-fed6e4e30025?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/minecraft-shaderhub-v5.1.apk',
    fileName: 'minecraft-shaderhub-v5.1.apk',
    fileSize: '45.0 MB',
    version: 'v5.1.4',
    category: 'Online Gaming & Esports',
    type: 'apk',
    accessType: 'PAID',
    price: 99,
    currency: 'BDT',
    downloadsCount: 11200,
    published: true,
    developer: 'CraftStudio Global',
    packageId: 'com.craftstudio.shaderhub',
    minAndroidVersion: 'Android 9.0+',
    sha256Checksum: 'd4e5f60718293a4b5c6d7e8f90123456789abcdef0123456789abcdef4',
    changelog: ['Compatible with Minecraft Bedrock 1.21.30', 'Ultra RTX Deferred lighting shaders added'],
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-28T16:00:00.000Z'
  },
  {
    id: 'apk-5',
    title: 'Roblox FPS Unlocker & Lua Script Studio Mobile',
    description: 'Unlock 144Hz refresh rate, customize graphic sliders, and debug custom Lua mini-games on mobile.',
    detailedNotes: 'Dedicated developer and enthusiast utility for Roblox mobile platform. Provides FPS monitoring, RAM cleaner, and script syntax preview.',
    thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/roblox-fps-studio-v2.1.apk',
    fileName: 'roblox-fps-studio-v2.1.apk',
    fileSize: '16.4 MB',
    version: 'v2.1.0',
    category: 'Online Gaming & Esports',
    type: 'apk',
    accessType: 'PAID',
    price: 49,
    currency: 'BDT',
    downloadsCount: 5430,
    published: true,
    developer: 'BloxTech Devs',
    packageId: 'com.bloxtech.fpsstudio',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: 'e5f60718293a4b5c6d7e8f90123456789abcdef0123456789abcdef5',
    changelog: ['120FPS bypass for high-end flagship displays', 'Reduced CPU overhead'],
    createdAt: '2026-08-15T12:00:00.000Z',
    updatedAt: '2026-08-29T10:00:00.000Z'
  },
  {
    id: 'apk-6',
    title: 'Genshin Impact Interactive Map & Wish Tracker',
    description: 'Offline interactive Teyvat map, oculi & chest locator, material farming routes, and pity counter.',
    detailedNotes: 'High-speed offline-capable map with artifact route optimizer, character ascension calculator, and cloud sync for marked pins.',
    thumbnail: 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/genshin-companion-v4.0.apk',
    fileName: 'genshin-companion-v4.0.apk',
    fileSize: '58.2 MB',
    version: 'v4.0.5',
    category: 'Online Gaming & Esports',
    type: 'apk',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    downloadsCount: 7890,
    published: true,
    developer: 'Teyvat Guides Team',
    packageId: 'com.teyvat.companion',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: 'f60718293a4b5c6d7e8f90123456789abcdef0123456789abcdef6',
    changelog: ['Added Natlan region pins and hidden chest routes', 'Wish pity rate visualizer'],
    createdAt: '2026-08-16T14:00:00.000Z',
    updatedAt: '2026-08-30T11:00:00.000Z'
  },
  {
    id: 'apk-7',
    title: 'Clash of Clans War Base Layouts & CWL Planner',
    description: 'One-click copy Town Hall 16 & Builder Hall 10 anti-3-star war base layouts with Clan War League planner.',
    detailedNotes: 'Over 5,000 top legend league base links with direct in-game copy integration. Includes war attack planner and army composition damage calculator.',
    thumbnail: 'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/coc-base-planner-v3.8.apk',
    fileName: 'coc-base-planner-v3.8.apk',
    fileSize: '24.1 MB',
    version: 'v3.8.0',
    category: 'Online Gaming & Esports',
    type: 'apk',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    downloadsCount: 9340,
    published: true,
    developer: 'Chief Clash Apps',
    packageId: 'com.chief.cocplanner',
    minAndroidVersion: 'Android 7.0+',
    sha256Checksum: '0718293a4b5c6d7e8f90123456789abcdef0123456789abcdef7',
    changelog: ['Updated TH16 Root Rider defense bases', 'Added Clan Capital raid layout tracker'],
    createdAt: '2026-08-17T15:00:00.000Z',
    updatedAt: '2026-08-30T14:00:00.000Z'
  },
  {
    id: 'apk-8',
    title: '8 Ball Pool Long Line Guideline Tool Pro',
    description: 'Geometric shot line extension, bank shot trajectory visualizer, and table spin physics assistant.',
    detailedNotes: 'Non-invasive overlay that accurately projects 2-cushion and 3-cushion bank shots using standard Euclidean geometry physics engine.',
    thumbnail: 'https://images.unsplash.com/photo-1588702547919-26089e690ecc?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/pool-guideline-v6.0.apk',
    fileName: 'pool-guideline-v6.0.apk',
    fileSize: '11.8 MB',
    version: 'v6.0.1',
    category: 'Online Gaming & Esports',
    type: 'apk',
    accessType: 'PAID',
    price: 149,
    currency: 'BDT',
    downloadsCount: 4890,
    published: true,
    developer: 'CueMaster Labs',
    packageId: 'com.cuemaster.guideline',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: '18293a4b5c6d7e8f90123456789abcdef0123456789abcdef8',
    changelog: ['3-cushion bank trajectory accuracy improved by 40%', 'Zero lag screen overlay'],
    createdAt: '2026-08-18T10:00:00.000Z',
    updatedAt: '2026-08-31T09:00:00.000Z'
  },
  {
    id: 'apk-9',
    title: 'eFootball PES 2026 Tactics & Formations Studio',
    description: 'Pro eFootball squad builder, manager tactical presets, player max stat training guides, and skill trainers.',
    detailedNotes: 'Complete database of managers, hidden formation setups, player progression points, and best booster skills for competitive Division 1 players.',
    thumbnail: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/efootball-tactics-v2.4.apk',
    fileName: 'efootball-tactics-v2.4.apk',
    fileSize: '31.5 MB',
    version: 'v2.4.3',
    category: 'Online Gaming & Esports',
    type: 'apk',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    downloadsCount: 6120,
    published: true,
    developer: 'PESHub Bangladesh',
    packageId: 'com.peshub.tacticsstudio',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: '293a4b5c6d7e8f90123456789abcdef0123456789abcdef9',
    changelog: ['Updated season 2026 player max attributes', 'Manager individual instructions guide'],
    createdAt: '2026-08-19T16:00:00.000Z',
    updatedAt: '2026-08-31T12:00:00.000Z'
  },
  {
    id: 'apk-10',
    title: 'Call of Duty Warzone Mobile Loadout & Meta Vault',
    description: 'Top tournament weapon attachments, zero-recoil build setups, TTK graphs, and battle pass tracker.',
    detailedNotes: 'Real-time weapon stat analyzer showing damage drop-off, bullet velocity, sprint-to-fire times, and recoil stabilization builds.',
    thumbnail: 'https://images.unsplash.com/photo-1542751110-97427bbecf20?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/codm-meta-vault-v1.7.apk',
    fileName: 'codm-meta-vault-v1.7.apk',
    fileSize: '19.8 MB',
    version: 'v1.7.2',
    category: 'Online Gaming & Esports',
    type: 'apk',
    accessType: 'PAID',
    price: 49,
    currency: 'BDT',
    downloadsCount: 3750,
    published: true,
    developer: 'Warzone Meta Team',
    packageId: 'com.warzonemeta.vault',
    minAndroidVersion: 'Android 9.0+',
    sha256Checksum: '3a4b5c6d7e8f90123456789abcdef0123456789abcdef10',
    changelog: ['Season 6 weapon balance updates', 'Added sniper 1-shot range calculator'],
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-31T15:00:00.000Z'
  },

  // 11-20: Developer & System Tools
  {
    id: 'apk-11',
    title: 'Termux Ultimate Linux Terminal Suite Pro',
    description: 'Complete Linux environment simulation with apt packages, Python 3.12, Node.js 22, Git, and Rust compiler.',
    detailedNotes: 'The premier open-source Android terminal emulator with X11 window server integration, hardware access plugins, and zero root requirements.',
    thumbnail: 'https://images.unsplash.com/photo-1629654297299-c8506221ca97?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/termux-ultimate-v0.118.apk',
    fileName: 'termux-ultimate-v0.118.apk',
    fileSize: '97.4 MB',
    version: 'v0.118.5',
    category: 'Developer Tools',
    type: 'apk',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    downloadsCount: 28400,
    published: true,
    developer: 'Termux Open Source Community',
    packageId: 'com.termux.ultimate',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: '4b5c6d7e8f90123456789abcdef0123456789abcdef11',
    changelog: ['Bundled with modern mirror list', 'Full support for ARM64 and x86_64 architectures'],
    createdAt: '2026-08-05T08:00:00.000Z',
    updatedAt: '2026-08-29T11:00:00.000Z'
  },
  {
    id: 'apk-12',
    title: 'CodeFlow Mobile IDE & JavaScript Sandbox',
    description: 'High-speed code editor with syntax highlighting for 50+ languages, Git clone, and local server preview.',
    detailedNotes: 'Write and test HTML/CSS/JS, TypeScript, Python, and C code right on your smartphone with split-screen live preview and terminal.',
    thumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/codeflow-studio-v2.4.apk',
    fileName: 'codeflow-studio-v2.4.apk',
    fileSize: '24.6 MB',
    version: 'v2.4.8',
    category: 'Developer Tools',
    type: 'apk',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    downloadsCount: 15600,
    published: true,
    developer: 'CodeCraft Mobile',
    packageId: 'com.codecraft.codeflow',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: '5c6d7e8f90123456789abcdef0123456789abcdef12',
    changelog: ['Added Monaco editor core', 'IntelliSense autocompletion for React and Tailwind'],
    createdAt: '2026-08-08T09:00:00.000Z',
    updatedAt: '2026-08-28T14:00:00.000Z'
  },
  {
    id: 'apk-13',
    title: 'Apktool M & Reverse Engineering Studio',
    description: 'Decompile, disassemble Smali, modify manifests, sign APKs, and analyze Android binary DEX architectures.',
    detailedNotes: 'Industry-standard APK modification tool ported natively to Android. Supports AAPT2 compiling, anti-split APK merging, and signature generation.',
    thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/apktool-m-studio-v2.4.apk',
    fileName: 'apktool-m-studio-v2.4.apk',
    fileSize: '15.8 MB',
    version: 'v2.4.1',
    category: 'Developer Tools',
    type: 'apk',
    accessType: 'PAID',
    price: 99,
    currency: 'BDT',
    downloadsCount: 8210,
    published: true,
    developer: 'Maximoff Dev Team',
    packageId: 'ru.maximoff.apktool',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: '6d7e8f90123456789abcdef0123456789abcdef13',
    changelog: ['Full support for Android 15 AAPT2 resources', 'Smali v3.0.8 compiler integrated'],
    createdAt: '2026-08-11T13:00:00.000Z',
    updatedAt: '2026-08-27T17:00:00.000Z'
  },
  {
    id: 'apk-14',
    title: 'HTTP Canar Packet Capture & SSL Sniffer',
    description: 'Capture, inspect, and rewrite HTTP/HTTPS/WebSocket network traffic with custom CA certificate installer.',
    detailedNotes: 'Powerful debugging proxy for mobile API developers. Inspect JSON payloads, simulate network latency, and mock server responses.',
    thumbnail: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/httpcanary-packet-v3.3.apk',
    fileName: 'httpcanary-packet-v3.3.apk',
    fileSize: '18.3 MB',
    version: 'v3.3.6',
    category: 'Developer Tools',
    type: 'apk',
    accessType: 'PAID',
    price: 149,
    currency: 'BDT',
    downloadsCount: 4600,
    published: true,
    developer: 'Guoshi Network Security',
    packageId: 'com.guoshi.httpcanary',
    minAndroidVersion: 'Android 9.0+',
    sha256Checksum: '7e8f90123456789abcdef0123456789abcdef14',
    changelog: ['TLS 1.3 decrypter updates', 'Export HAR and Postman collection format'],
    createdAt: '2026-08-13T10:00:00.000Z',
    updatedAt: '2026-08-30T10:00:00.000Z'
  },
  {
    id: 'apk-15',
    title: 'Shizuku & Wireless ADB Privilege Manager',
    description: 'Run elevated shell APIs without root access via Wireless ADB pairing on Android 11 through Android 15.',
    detailedNotes: 'Allows user apps to directly utilize system APIs with full permission safety. Supports IceBox, App Ops, and advanced automation tools.',
    thumbnail: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/shizuku-adb-v13.5.apk',
    fileName: 'shizuku-adb-v13.5.apk',
    fileSize: '6.4 MB',
    version: 'v13.5.4',
    category: 'Developer Tools',
    type: 'apk',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    downloadsCount: 19800,
    published: true,
    developer: 'Rikka System Labs',
    packageId: 'moe.shizuku.privileged.api',
    minAndroidVersion: 'Android 11.0+',
    sha256Checksum: '8f90123456789abcdef0123456789abcdef15',
    changelog: ['Fixed Android 15 wireless pairing port renegotiation', 'Updated Sui service module'],
    createdAt: '2026-08-04T07:00:00.000Z',
    updatedAt: '2026-08-25T09:00:00.000Z'
  },
  {
    id: 'apk-16',
    title: 'CPU-Z Hardware Monitor & SoC Benchmark Pro',
    description: 'Detailed CPU core frequencies, GPU thermal throttling curves, battery health percentages, and RAM analyzer.',
    detailedNotes: 'Real-time sensors monitor showing precise thermal zone readings, Vulkan/OpenGL capabilities, and deep chipset telemetry without advertisements.',
    thumbnail: 'https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/cpuz-hardware-v1.4.apk',
    fileName: 'cpuz-hardware-v1.4.apk',
    fileSize: '4.8 MB',
    version: 'v1.4.3',
    category: 'Security & Networking',
    type: 'apk',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    downloadsCount: 12400,
    published: true,
    developer: 'CPUID & Silicon Labs',
    packageId: 'com.cpuid.cpu_z_pro',
    minAndroidVersion: 'Android 7.0+',
    sha256Checksum: '90123456789abcdef0123456789abcdef16',
    changelog: ['Added Snapdragon 8 Gen 4 and Dimensity 9400 SoC definitions', 'New battery cycle count reader'],
    createdAt: '2026-08-07T12:00:00.000Z',
    updatedAt: '2026-08-26T16:00:00.000Z'
  },
  {
    id: 'apk-17',
    title: 'NetGuard Pro Firewall & Ad-Blocking Gateway',
    description: 'No-root VPN firewall blocking unwanted telemetry, background tracking, and ad servers per individual app.',
    detailedNotes: 'Inspects outgoing IP addresses, logs DNS requests, and restricts bandwidth usage to save mobile data and prolong battery life.',
    thumbnail: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/netguard-firewall-v3.0.apk',
    fileName: 'netguard-firewall-v3.0.apk',
    fileSize: '12.8 MB',
    version: 'v3.0.2',
    category: 'Security & Networking',
    type: 'apk',
    accessType: 'PAID',
    price: 99,
    currency: 'BDT',
    downloadsCount: 7120,
    published: true,
    developer: 'Marcel Bokhorst Labs',
    packageId: 'eu.faircode.netguard',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: '0123456789abcdef0123456789abcdef17',
    changelog: ['Added DNS-over-TLS (DoT) provider switching', 'New traffic graphs in dark mode'],
    createdAt: '2026-08-09T14:00:00.000Z',
    updatedAt: '2026-08-27T10:00:00.000Z'
  },
  {
    id: 'apk-18',
    title: 'AdAway DNS Hosts Blocker & Privacy Vault',
    description: 'System-wide ad blocker using custom hosts list, local DNS webserver, and zero-ad experience across all apps.',
    detailedNotes: 'Eliminates popup ads, trackers, and malicious phishing domains on both rooted and non-rooted devices using local VPN DNS redirection.',
    thumbnail: 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/adaway-vault-v6.1.apk',
    fileName: 'adaway-vault-v6.1.apk',
    fileSize: '10.5 MB',
    version: 'v6.1.1',
    category: 'Security & Networking',
    type: 'apk',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    downloadsCount: 16800,
    published: true,
    developer: 'AdAway Open Source',
    packageId: 'org.adaway',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: '123456789abcdef0123456789abcdef18',
    changelog: ['Auto-updating blocking lists from 15 global providers', 'Whitelisting assistant for payment apps'],
    createdAt: '2026-08-03T11:00:00.000Z',
    updatedAt: '2026-08-24T13:00:00.000Z'
  },
  {
    id: 'apk-19',
    title: 'Kiwi Browser Next & Chrome Extensions Engine',
    description: 'Chromium-based fast mobile browser with native desktop Chrome Extension support, DevTools, and ad-blocker.',
    detailedNotes: 'Install uBlock Origin, Tampermonkey, React DevTools, and MetaMask directly on Android with night mode and bottom address bar.',
    thumbnail: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/kiwi-browser-v124.apk',
    fileName: 'kiwi-browser-v124.apk',
    fileSize: '88.5 MB',
    version: 'v124.0.6',
    category: 'Productivity & Utilities',
    type: 'apk',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    downloadsCount: 22100,
    published: true,
    developer: 'Geometry OU',
    packageId: 'com.kiwibrowser.browser',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: '23456789abcdef0123456789abcdef19',
    changelog: ['Updated Chromium engine to v124', 'Improved Manifest V3 extension compatibility'],
    createdAt: '2026-08-02T10:00:00.000Z',
    updatedAt: '2026-08-23T15:00:00.000Z'
  },
  {
    id: 'apk-20',
    title: 'Solid Explorer Dual-Pane Cloud File Manager Pro',
    description: 'Dual-panel file manager with root access, SMB/FTP/WebDAV integration, archive extractor, and cloud encryption.',
    detailedNotes: 'Browse local files and cloud drives side-by-side with drag-and-drop support, fingerprint protection, and media previewers.',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/solid-explorer-v2.8.apk',
    fileName: 'solid-explorer-v2.8.apk',
    fileSize: '21.4 MB',
    version: 'v2.8.35',
    category: 'Productivity & Utilities',
    type: 'apk',
    accessType: 'PAID',
    price: 99,
    currency: 'BDT',
    downloadsCount: 9450,
    published: true,
    developer: 'NeatBytes Software',
    packageId: 'pl.solidexplorer2',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: '3456789abcdef0123456789abcdef20',
    changelog: ['Added Google Drive 2026 OAuth token refresh', 'Material You dynamic color styling'],
    createdAt: '2026-08-06T15:00:00.000Z',
    updatedAt: '2026-08-29T12:00:00.000Z'
  },

  // 21-35: Media, Video Editing, Audio & Creative Tools
  {
    id: 'apk-21',
    title: 'CapCut Video Editor Pro VFX & 4K Presets',
    description: 'Multi-layer timeline editing, AI smart cutouts, keyframe animations, smooth slow-motion, and 4K 60fps export.',
    detailedNotes: 'The premier video editing engine with trending TikTok/Reels transitions, auto-captioning, audio isolation, and color grading filters.',
    thumbnail: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/capcut-pro-v11.2.apk',
    fileName: 'capcut-pro-v11.2.apk',
    fileSize: '142.0 MB',
    version: 'v11.2.0',
    category: 'Media, Video & Audio',
    type: 'apk',
    accessType: 'PAID',
    price: 149,
    currency: 'BDT',
    downloadsCount: 31200,
    published: true,
    developer: 'Bytedance Creative',
    packageId: 'com.lemon.lvoverseas',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: '456789abcdef0123456789abcdef21',
    changelog: ['Added AI Voice Dubbing in Bengali and English', 'Export bitrates up to 100Mbps'],
    createdAt: '2026-08-10T08:00:00.000Z',
    updatedAt: '2026-08-30T16:00:00.000Z'
  },
  {
    id: 'apk-22',
    title: 'Alight Motion Graphic Animation & VFX Suite Pro',
    description: 'First professional motion design app for smartphone with vector graphics, visual effects, and velocity curves.',
    detailedNotes: 'Supports XML preset imports, multi-layer grouping, blend modes, motion blur, and customizable easing curve graphs for animators.',
    thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/alight-motion-v5.0.apk',
    fileName: 'alight-motion-v5.0.apk',
    fileSize: '118.5 MB',
    version: 'v5.0.260',
    category: 'Media, Video & Audio',
    type: 'apk',
    accessType: 'PAID',
    price: 199,
    currency: 'BDT',
    downloadsCount: 18400,
    published: true,
    developer: 'Alight Creative Inc',
    packageId: 'com.alightcreative.motion',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: '56789abcdef0123456789abcdef22',
    changelog: ['New Null Object tracking layers', 'GPU accelerated rendering pipeline'],
    createdAt: '2026-08-12T14:00:00.000Z',
    updatedAt: '2026-08-28T18:00:00.000Z'
  },
  {
    id: 'apk-23',
    title: 'Kinemaster Video Studio 4K Multi-Track Master',
    description: 'Full-featured mobile video editing studio with Chroma Key green screen, audio ducking, and asset store access.',
    detailedNotes: 'Precision frame-by-frame trimming, volume envelope controls, 3D transition packages, and support for high bit-depth H.265 video.',
    thumbnail: 'https://images.unsplash.com/photo-1536240478700-b869070f9279?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/kinemaster-pro-v7.4.apk',
    fileName: 'kinemaster-pro-v7.4.apk',
    fileSize: '95.6 MB',
    version: 'v7.4.15',
    category: 'Media, Video & Audio',
    type: 'apk',
    accessType: 'PAID',
    price: 99,
    currency: 'BDT',
    downloadsCount: 14500,
    published: true,
    developer: 'KineMaster Corporation',
    packageId: 'com.nexstreaming.app.kinemasterfree',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: '6789abcdef0123456789abcdef23',
    changelog: ['Fixed audio desync bug on 120Hz displays', 'Unlimited video layers on Snapdragon 8 series'],
    createdAt: '2026-08-14T09:00:00.000Z',
    updatedAt: '2026-08-29T11:00:00.000Z'
  },
  {
    id: 'apk-24',
    title: 'VLC Pro Media Player & Network Streamer',
    description: 'Plays any video and audio file codec (MKV, MP4, AVI, FLAC, AC3) with subtitle download and local network SMB/DLNA streaming.',
    detailedNotes: 'Hardware acceleration with zero ads, multi-track audio selection, aspect ratio tweaking, and picture-in-picture background playback.',
    thumbnail: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/vlc-player-v3.5.apk',
    fileName: 'vlc-player-v3.5.apk',
    fileSize: '36.8 MB',
    version: 'v3.5.4',
    category: 'Media, Video & Audio',
    type: 'apk',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    downloadsCount: 26500,
    published: true,
    developer: 'VideoLAN Organization',
    packageId: 'org.videolan.vlc',
    minAndroidVersion: 'Android 7.0+',
    sha256Checksum: '789abcdef0123456789abcdef24',
    changelog: ['AV1 hardware decoding optimization', 'Subscene auto subtitle search restored'],
    createdAt: '2026-08-01T12:00:00.000Z',
    updatedAt: '2026-08-26T15:00:00.000Z'
  },
  {
    id: 'apk-25',
    title: 'MX Player Custom Codec Suite Pro',
    description: 'Custom ARM64 Neon codec package unlocking DTS, AC3, EAC3, and TrueHD high-definition audio playback.',
    detailedNotes: 'Solves the silent audio problem on downloaded 4K HDR movie files. Full multi-core decoding boost with gesture playback controls.',
    thumbnail: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/mx-player-codecs-v1.8.apk',
    fileName: 'mx-player-codecs-v1.8.apk',
    fileSize: '48.2 MB',
    version: 'v1.8.4',
    category: 'Media, Video & Audio',
    type: 'apk',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    downloadsCount: 19300,
    published: true,
    developer: 'J2 Interactive Labs',
    packageId: 'com.mxtech.videoplayer.ad',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: '89abcdef0123456789abcdef25',
    changelog: ['DTS-HD and Dolby Atmos software decoders updated', 'Supports Android 15 volume gain'],
    createdAt: '2026-08-08T10:00:00.000Z',
    updatedAt: '2026-08-27T14:00:00.000Z'
  },
  {
    id: 'apk-26',
    title: 'PixelLab 3D Typography & Banner Studio Pro',
    description: 'Create professional YouTube thumbnails, 3D text logos, poster typography, and social banners with custom fonts.',
    detailedNotes: 'Includes 1,000+ pre-installed Bengali and English fonts, shadow extrusion, gradient fills, sticker packs, and high-res PNG export.',
    thumbnail: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/pixellab-pro-v2.1.apk',
    fileName: 'pixellab-pro-v2.1.apk',
    fileSize: '38.4 MB',
    version: 'v2.1.3',
    category: 'Media, Video & Audio',
    type: 'apk',
    accessType: 'PAID',
    price: 49,
    currency: 'BDT',
    downloadsCount: 16700,
    published: true,
    developer: 'App Holdings Imaging',
    packageId: 'com.imaginstudio.imagetools.pixellab',
    minAndroidVersion: 'Android 7.0+',
    sha256Checksum: '9abcdef0123456789abcdef26',
    changelog: ['Added curved text and perspective warping tool', 'Direct PLP project file cloud backup'],
    createdAt: '2026-08-11T16:00:00.000Z',
    updatedAt: '2026-08-30T13:00:00.000Z'
  },
  {
    id: 'apk-27',
    title: 'Snapseed Pro HDR Photo Editor & LUTs',
    description: 'Google professional photo editor with selective brightness tuning, healing brush, double exposure, and RAW DNG support.',
    detailedNotes: 'Non-destructive 29-tool photo suite including curve controls, white balance, perspective tilt-shift, and exportable look presets.',
    thumbnail: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/snapseed-pro-v2.21.apk',
    fileName: 'snapseed-pro-v2.21.apk',
    fileSize: '29.5 MB',
    version: 'v2.21.0',
    category: 'Media, Video & Audio',
    type: 'apk',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    downloadsCount: 24100,
    published: true,
    developer: 'Nik Photography Labs',
    packageId: 'com.niksoftware.snapseed',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: 'abcdef0123456789abcdef27',
    changelog: ['Enhanced AI portrait skin texture smoothing', 'Support for 100MP camera RAW files'],
    createdAt: '2026-08-04T13:00:00.000Z',
    updatedAt: '2026-08-25T11:00:00.000Z'
  },
  {
    id: 'apk-28',
    title: 'AudioMaster Studio Pro Mobile DAW',
    description: '32-track wave audio recording, vocal noise removal, parametric 10-band equalizer, and lossless FLAC mastering.',
    detailedNotes: 'Real-time 32-bit floating point audio engine supporting external USB audio interfaces, low-latency monitoring, and pitch correction.',
    thumbnail: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/audiomaster-daw-v4.2.apk',
    fileName: 'audiomaster-daw-v4.2.apk',
    fileSize: '34.6 MB',
    version: 'v4.2.2',
    category: 'Media, Video & Audio',
    type: 'apk',
    accessType: 'PAID',
    price: 199,
    currency: 'BDT',
    downloadsCount: 5200,
    published: true,
    developer: 'SonicWorks Audio',
    packageId: 'com.sonicworks.audiomaster',
    minAndroidVersion: 'Android 10.0+',
    sha256Checksum: 'bcdef0123456789abcdef28',
    changelog: ['Added AI background hiss and fan noise remover', 'MIDI velocity sensitivity calibrator'],
    createdAt: '2026-08-15T15:00:00.000Z',
    updatedAt: '2026-08-31T14:00:00.000Z'
  },
  {
    id: 'apk-29',
    title: 'Screen Recorder 4K 120FPS & Internal Audio Pro',
    description: 'Lag-free gameplay screen recorder with crisp internal game sound, facecam overlay, and live RTMP streaming.',
    detailedNotes: 'Record competitive gameplays at up to 120 FPS in 2K/4K resolution without watermarks. Includes brush drawing tool and video trimmer.',
    thumbnail: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/screen-recorder-v5.3.apk',
    fileName: 'screen-recorder-v5.3.apk',
    fileSize: '17.2 MB',
    version: 'v5.3.1',
    category: 'Media, Video & Audio',
    type: 'apk',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    downloadsCount: 15400,
    published: true,
    developer: 'InShot Video Tech',
    packageId: 'videoeditor.videorecorder.screenrecorder',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: 'cdef0123456789abcdef29',
    changelog: ['Lossless 60Mbps bitrate mode added', 'Android 14/15 system sound recording fix'],
    createdAt: '2026-08-06T11:00:00.000Z',
    updatedAt: '2026-08-28T10:00:00.000Z'
  },
  {
    id: 'apk-30',
    title: 'Wavelet Headphone Equalizer & AutoEq Studio',
    description: 'Over 3,400 headphone specific tuning profiles, 9-band graphic EQ, bass booster, and virtualizer for music lovers.',
    detailedNotes: 'Automatically applies Harman Target curve corrections to popular earphones and TWS earbuds (Sony, Apple, Samsung, Realme, QCY).',
    thumbnail: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/wavelet-autoeq-v24.0.apk',
    fileName: 'wavelet-autoeq-v24.0.apk',
    fileSize: '7.8 MB',
    version: 'v24.0.8',
    category: 'Media, Video & Audio',
    type: 'apk',
    accessType: 'PAID',
    price: 49,
    currency: 'BDT',
    downloadsCount: 8900,
    published: true,
    developer: 'Pittvandewitt Labs',
    packageId: 'com.pittvandewitt.wavelet',
    minAndroidVersion: 'Android 9.0+',
    sha256Checksum: 'def0123456789abcdef30',
    changelog: ['Updated 2026 headphone database with 200 new models', 'System-wide DUMP audio fix'],
    createdAt: '2026-08-13T12:00:00.000Z',
    updatedAt: '2026-08-30T17:00:00.000Z'
  },

  // 31-50: Productivity, Custom Launchers, Automation & Utilities
  {
    id: 'apk-31',
    title: 'Nova Launcher Prime & Gesture Customizer',
    description: 'Ultra-fast, deeply customizable home screen launcher with custom icon scaling, subgrid positioning, and swipe gestures.',
    detailedNotes: 'The benchmark Android launcher offering extreme fluid animations, dock styling, hidden app drawer folders, and infinite backup possibilities.',
    thumbnail: 'https://images.unsplash.com/photo-1616469829941-c7200edec809?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/nova-launcher-v8.1.apk',
    fileName: 'nova-launcher-v8.1.apk',
    fileSize: '15.4 MB',
    version: 'v8.1.2',
    category: 'Productivity & Utilities',
    type: 'apk',
    accessType: 'PAID',
    price: 99,
    currency: 'BDT',
    downloadsCount: 21400,
    published: true,
    developer: 'TeslaCoil Software',
    packageId: 'com.teslacoilsw.launcher.prime',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: 'ef0123456789abcdef31',
    changelog: ['Material You dynamic tinting engine', 'Fluid predictive back gesture animations'],
    createdAt: '2026-08-02T16:00:00.000Z',
    updatedAt: '2026-08-27T11:00:00.000Z'
  },
  {
    id: 'apk-32',
    title: 'Tasker Automation Engine & Custom Action Suite',
    description: 'Total device automation: triggers, context profiles, auto WiFi toggles, SMS responders, and battery savers.',
    detailedNotes: 'The most comprehensive Android automation powerhouse with over 350 system actions, webhook triggers, scene builders, and rootless ADB integration.',
    thumbnail: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/tasker-automation-v6.3.apk',
    fileName: 'tasker-automation-v6.3.apk',
    fileSize: '18.9 MB',
    version: 'v6.3.13',
    category: 'Productivity & Utilities',
    type: 'apk',
    accessType: 'PAID',
    price: 149,
    currency: 'BDT',
    downloadsCount: 11200,
    published: true,
    developer: 'joaomgcd Labs',
    packageId: 'net.dinglisch.android.taskerm',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: 'f0123456789abcdef32',
    changelog: ['Added AI Gemini prompt trigger action', 'Direct Shizuku privileged command execution'],
    createdAt: '2026-08-07T14:00:00.000Z',
    updatedAt: '2026-08-29T15:00:00.000Z'
  },
  {
    id: 'apk-33',
    title: 'Telegram X Turbo & Supercharged Client',
    description: 'Blazing-fast alternative Telegram client built in pure TDLib with smooth physics animations, multiple accounts, and tab tabs.',
    detailedNotes: 'Saves 30% battery compared to standard clients. Features customized chat bubbles, instant file caching, and custom sticker organizers.',
    thumbnail: 'https://images.unsplash.com/photo-1614680376593-902f749f7ffc?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/telegram-x-v0.26.apk',
    fileName: 'telegram-x-v0.26.apk',
    fileSize: '32.1 MB',
    version: 'v0.26.8',
    category: 'Productivity & Utilities',
    type: 'apk',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    downloadsCount: 29500,
    published: true,
    developer: 'Telegram LLC',
    packageId: 'org.thunderdog.challegram',
    minAndroidVersion: 'Android 7.0+',
    sha256Checksum: '0123456789abcdef33',
    changelog: ['Added message translation to Bengali', '60FPS sticker rendering optimization'],
    createdAt: '2026-08-05T13:00:00.000Z',
    updatedAt: '2026-08-28T16:00:00.000Z'
  },
  {
    id: 'apk-34',
    title: 'FocusTrack Daily Pomodoro & Habit Sync',
    description: 'Minimalist, distraction-free productivity timer with soundscapes, widget support, and offline encrypted sync.',
    detailedNotes: 'Crafted with extreme attention to battery efficiency and clean typography. Supports custom work cycles, tagged tasks, and streak backups.',
    thumbnail: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/focustrack-v1.8.apk',
    fileName: 'focustrack-v1.8.apk',
    fileSize: '8.2 MB',
    version: 'v1.8.0',
    category: 'Productivity & Utilities',
    type: 'apk',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    downloadsCount: 8400,
    published: true,
    developer: 'Zenith Apps',
    packageId: 'com.zenith.focustrack',
    minAndroidVersion: 'Android 7.0+',
    sha256Checksum: '123456789abcdef34',
    changelog: ['Added binaural ambient rain & coffee shop sound generator', 'Reduced memory footprint'],
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-20T11:00:00.000Z'
  },
  {
    id: 'apk-35',
    title: 'AppLock Pro Fingerprint & Intruder Selfie Vault',
    description: 'Lock WhatsApp, Gallery, and Payment apps with biometric fingerprint, fake crash screens, and hidden vault.',
    detailedNotes: 'Takes secret photo of anyone attempting wrong PIN. Encrypts photos and videos in hidden vault with zero cloud leakage.',
    thumbnail: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/applock-pro-v5.4.apk',
    fileName: 'applock-pro-v5.4.apk',
    fileSize: '14.6 MB',
    version: 'v5.4.2',
    category: 'Security & Networking',
    type: 'apk',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    downloadsCount: 17200,
    published: true,
    developer: 'DoMobile Security Lab',
    packageId: 'com.domobile.applockwatcher',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: '23456789abcdef35',
    changelog: ['Improved in-display fingerprint responsiveness', 'Stealth icon disguise options'],
    createdAt: '2026-08-09T10:00:00.000Z',
    updatedAt: '2026-08-26T14:00:00.000Z'
  },
  {
    id: 'apk-36',
    title: 'Speedtest Master 5G & WiFi Heatmap Analyzer',
    description: 'Accurate internet speed test, ping jitter monitor, packet loss test, and WiFi signal strength mapper.',
    detailedNotes: 'Tests download and upload speeds up to 10Gbps on local Bangladesh ISP servers with real-time latency graphs.',
    thumbnail: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/speedtest-master-v4.1.apk',
    fileName: 'speedtest-master-v4.1.apk',
    fileSize: '16.0 MB',
    version: 'v4.1.9',
    category: 'Security & Networking',
    type: 'apk',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    downloadsCount: 13900,
    published: true,
    developer: 'SpeedCheck Tech',
    packageId: 'com.speed.wifi.speedtest.master',
    minAndroidVersion: 'Android 7.0+',
    sha256Checksum: '3456789abcdef36',
    changelog: ['Added 5G NR signal channel analyzer', 'Export speed test certificate as image'],
    createdAt: '2026-08-11T11:00:00.000Z',
    updatedAt: '2026-08-27T15:00:00.000Z'
  },
  {
    id: 'apk-37',
    title: 'WPS Office Pro Suite & PDF Form Filler',
    description: 'All-in-one document editor for Word (.docx), Excel (.xlsx), PowerPoint (.pptx), with PDF scanner and e-signature.',
    detailedNotes: 'Complete mobile office suite with zero advertising. Supports template galleries, cloud drive syncing, and high-speed PDF conversion.',
    thumbnail: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/wps-office-v18.2.apk',
    fileName: 'wps-office-v18.2.apk',
    fileSize: '98.5 MB',
    version: 'v18.2.4',
    category: 'Productivity & Utilities',
    type: 'apk',
    accessType: 'PAID',
    price: 99,
    currency: 'BDT',
    downloadsCount: 18200,
    published: true,
    developer: 'Kingsoft Office Software',
    packageId: 'cn.wps.moffice_eng',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: '456789abcdef37',
    changelog: ['Added AI Document Summarizer', 'PDF OCR optical character reader improved'],
    createdAt: '2026-08-04T09:00:00.000Z',
    updatedAt: '2026-08-25T16:00:00.000Z'
  },
  {
    id: 'apk-38',
    title: 'SD Maid 2 / SE System Cleaning & Storage Master',
    description: 'Thorough system cleaner finding corpse files, cleaning app caches, finding duplicate files, and optimizing databases.',
    detailedNotes: 'Open-source storage maintenance tool utilizing modern Storage Access Framework and Shizuku to reclaim gigabytes of junk files safely.',
    thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/sdmaid-se-v0.22.apk',
    fileName: 'sdmaid-se-v0.22.apk',
    fileSize: '13.4 MB',
    version: 'v0.22.1',
    category: 'Security & Networking',
    type: 'apk',
    accessType: 'PAID',
    price: 49,
    currency: 'BDT',
    downloadsCount: 10400,
    published: true,
    developer: 'Darken Apps',
    packageId: 'eu.darken.sdmse',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: '56789abcdef38',
    changelog: ['Full compatibility with Android 15 storage restrictions', 'CorpseFinder heuristics updated'],
    createdAt: '2026-08-08T12:00:00.000Z',
    updatedAt: '2026-08-28T14:00:00.000Z'
  },
  {
    id: 'apk-39',
    title: 'Kustom Live Wallpaper (KLWP) Pro Maker',
    description: 'Create incredible animated Android home screen live wallpapers with digital clocks, weather animations, and music bars.',
    detailedNotes: 'Build completely custom UI animations with complex formulas, gyro 3D parallax effects, touch triggers, and dynamic RSS feeds.',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/klwp-maker-v3.74.apk',
    fileName: 'klwp-maker-v3.74.apk',
    fileSize: '28.0 MB',
    version: 'v3.74.0',
    category: 'Productivity & Utilities',
    type: 'apk',
    accessType: 'PAID',
    price: 149,
    currency: 'BDT',
    downloadsCount: 6800,
    published: true,
    developer: 'Kustom Industries',
    packageId: 'org.kustom.wallpaper',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: '6789abcdef39',
    changelog: ['Added dynamic battery graph formulas', '60FPS rendering optimizations'],
    createdAt: '2026-08-10T14:00:00.000Z',
    updatedAt: '2026-08-30T10:00:00.000Z'
  },
  {
    id: 'apk-40',
    title: 'Bitwarden Password Vault & 2FA Authenticator',
    description: 'End-to-end encrypted password manager with passkey support, autofill engine, and built-in two-factor authenticator.',
    detailedNotes: 'Open-source security vault storing logins, credit cards, secure notes, and TOTP keys with zero-knowledge AES-256 bit encryption.',
    thumbnail: 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/bitwarden-vault-v2026.8.apk',
    fileName: 'bitwarden-vault-v2026.8.apk',
    fileSize: '42.0 MB',
    version: 'v2026.8.0',
    category: 'Security & Networking',
    type: 'apk',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    downloadsCount: 21800,
    published: true,
    developer: 'Bitwarden Inc',
    packageId: 'com.x8bit.bitwarden',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: '789abcdef40',
    changelog: ['Native Passkey sync across Android and Chrome', 'Biometric quick-unlock speed increased'],
    createdAt: '2026-08-03T09:00:00.000Z',
    updatedAt: '2026-08-24T10:00:00.000Z'
  },
  {
    id: 'apk-41',
    title: 'AccuBattery Pro Battery Health & Charge Alarm',
    description: 'Accurate battery cycle wear calculation, live mA discharge monitor, charge speed tester, and 80% stop alarm.',
    detailedNotes: 'Prolongs battery lifespan by alerting at the optimal 80% charge threshold. Measures charging wattage and individual app power consumption.',
    thumbnail: 'https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/accubattery-pro-v2.1.apk',
    fileName: 'accubattery-pro-v2.1.apk',
    fileSize: '9.4 MB',
    version: 'v2.1.8',
    category: 'Security & Networking',
    type: 'apk',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    downloadsCount: 14700,
    published: true,
    developer: 'Digibites Battery Labs',
    packageId: 'com.digibites.accubattery',
    minAndroidVersion: 'Android 7.0+',
    sha256Checksum: '89abcdef41',
    changelog: ['120W / 150W ultra fast charging support', 'Dark OLED AMOLED theme updated'],
    createdAt: '2026-08-07T11:00:00.000Z',
    updatedAt: '2026-08-26T12:00:00.000Z'
  },
  {
    id: 'apk-42',
    title: 'RetroArch Multi-Console Emulator Pro Suite',
    description: 'All-in-one game console emulator frontend for PSP, PS1, N64, GBA, Arcade, and NES with shaders and save states.',
    detailedNotes: 'Modular libretro cores with zero input lag, netplay multiplayer, rewind support, and customizable touch control layouts.',
    thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/retroarch-emu-v1.18.apk',
    fileName: 'retroarch-emu-v1.18.apk',
    fileSize: '185.0 MB',
    version: 'v1.18.0',
    category: 'Online Gaming & Esports',
    type: 'apk',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    downloadsCount: 17800,
    published: true,
    developer: 'Libretro Open Team',
    packageId: 'com.retroarch.aarch64',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: '9abcdef42',
    changelog: ['Added Vulkan 1.3 video driver', 'New CRT-Royale shader presets for mobile'],
    createdAt: '2026-08-06T09:00:00.000Z',
    updatedAt: '2026-08-28T13:00:00.000Z'
  },
  {
    id: 'apk-43',
    title: 'PPSSPP Gold PSP Emulator 60FPS HD',
    description: 'Play Sony PSP games in 4K / 1080p resolution with texture filtering, gamepad support, and Vulkan acceleration.',
    detailedNotes: 'The premier PSP emulator running legendary titles (God of War, Tekken 6, Monster Hunter) smoothly at 60 FPS with custom control layouts.',
    thumbnail: 'https://images.unsplash.com/photo-1542751110-97427bbecf20?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/ppsspp-gold-v1.17.apk',
    fileName: 'ppsspp-gold-v1.17.apk',
    fileSize: '26.8 MB',
    version: 'v1.17.1',
    category: 'Online Gaming & Esports',
    type: 'apk',
    accessType: 'PAID',
    price: 99,
    currency: 'BDT',
    downloadsCount: 19400,
    published: true,
    developer: 'Henrik Rydgård',
    packageId: 'org.ppsspp.ppssppgold',
    minAndroidVersion: 'Android 7.0+',
    sha256Checksum: 'abcdef43',
    changelog: ['Fixed graphics glitch in Naruto Shippuden games', 'Support for modern Bluetooth game controllers'],
    createdAt: '2026-08-05T15:00:00.000Z',
    updatedAt: '2026-08-27T16:00:00.000Z'
  },
  {
    id: 'apk-44',
    title: 'Moonlight Game Streaming Client PC to Android',
    description: 'Stream PC games from NVIDIA or AMD host rigs at 4K 120FPS with HDR and ultra low 3ms network latency.',
    detailedNotes: 'Open-source Sunshine/NVIDIA GameStream client supporting wireless mouse/keyboard, Xbox/PS5 controllers, and 5.1 surround sound.',
    thumbnail: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/moonlight-stream-v12.2.apk',
    fileName: 'moonlight-stream-v12.2.apk',
    fileSize: '15.2 MB',
    version: 'v12.2.0',
    category: 'Online Gaming & Esports',
    type: 'apk',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    downloadsCount: 9100,
    published: true,
    developer: 'Moonlight Stream Team',
    packageId: 'com.limelight',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: 'bcdef44',
    changelog: ['Added AV1 hardware decoding stream support', 'Touchscreen custom on-screen joystick overlays'],
    createdAt: '2026-08-11T10:00:00.000Z',
    updatedAt: '2026-08-29T09:00:00.000Z'
  },
  {
    id: 'apk-45',
    title: 'AetherSX2 PS2 Emulator Mobile Ultimate',
    description: 'Play legendary PlayStation 2 games on high-end ARM64 Android phones with dual shock controller support.',
    detailedNotes: 'Vulkan and OpenGL backend with multi-threaded VU execution, up to 5x native resolution scaling, and widescreen 16:9 patches.',
    thumbnail: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/aethersx2-ps2-v1.5.apk',
    fileName: 'aethersx2-ps2-v1.5.apk',
    fileSize: '31.4 MB',
    version: 'v1.5-4248',
    category: 'Online Gaming & Esports',
    type: 'apk',
    accessType: 'PAID',
    price: 149,
    currency: 'BDT',
    downloadsCount: 22600,
    published: true,
    developer: 'Tenzin Software',
    packageId: 'xyz.aethersx2.android',
    minAndroidVersion: 'Android 9.0+',
    sha256Checksum: 'cdef45',
    changelog: ['Added Vulkan anisotropic texture filtering', 'Fixed sound stuttering in Gran Turismo 4'],
    createdAt: '2026-08-08T16:00:00.000Z',
    updatedAt: '2026-08-30T15:00:00.000Z'
  },
  {
    id: 'apk-46',
    title: 'ProtonVPN Secure & High-Speed Unlimited',
    description: 'Swiss-based high-security VPN with zero logs policy, Tor over VPN, and ultra-fast 10Gbps servers for gaming.',
    detailedNotes: 'Bypasses geo-restrictions and ISP throttling with strong ChaCha20 / AES-256 encryption and NetShield ad-blocker.',
    thumbnail: 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/protonvpn-secure-v5.4.apk',
    fileName: 'protonvpn-secure-v5.4.apk',
    fileSize: '38.0 MB',
    version: 'v5.4.18',
    category: 'Security & Networking',
    type: 'apk',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    downloadsCount: 16500,
    published: true,
    developer: 'Proton AG Switzerland',
    packageId: 'ch.protonvpn.android',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: 'def46',
    changelog: ['Added stealth WireGuard protocol', 'Optimized gaming server latency routes'],
    createdAt: '2026-08-02T11:00:00.000Z',
    updatedAt: '2026-08-25T13:00:00.000Z'
  },
  {
    id: 'apk-47',
    title: 'Krita Mobile Digital Painting & Concept Art',
    description: 'Full-featured desktop-grade digital painting and 2D animation studio optimized for stylus and tablets.',
    detailedNotes: 'Over 100 brush engines, layer blending modes, vector shapes, perspective drawing grids, and pressure sensitivity support for S-Pen.',
    thumbnail: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/krita-paint-v5.2.apk',
    fileName: 'krita-paint-v5.2.apk',
    fileSize: '135.0 MB',
    version: 'v5.2.3',
    category: 'Media, Video & Audio',
    type: 'apk',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    downloadsCount: 8700,
    published: true,
    developer: 'Krita Foundation',
    packageId: 'org.krita',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: 'ef47',
    changelog: ['Touch gestures for canvas rotation and zoom', 'New brush presets for comic illustration'],
    createdAt: '2026-08-10T11:00:00.000Z',
    updatedAt: '2026-08-29T17:00:00.000Z'
  },
  {
    id: 'apk-48',
    title: 'FL Studio Mobile Pro Music Production Studio',
    description: 'Create multi-track music projects, synthesizers, drum kits, audio recording, and export WAV/MP3 files.',
    detailedNotes: 'Complete music production studio with high quality samplers, step sequencer, piano roll editor, effect modules, and MIDI controller support.',
    thumbnail: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/fl-studio-mobile-v4.6.apk',
    fileName: 'fl-studio-mobile-v4.6.apk',
    fileSize: '240.0 MB',
    version: 'v4.6.4',
    category: 'Media, Video & Audio',
    type: 'apk',
    accessType: 'PAID',
    price: 350,
    currency: 'BDT',
    downloadsCount: 14800,
    published: true,
    developer: 'Image-Line Software',
    packageId: 'com.imageline.FLM',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: 'f48',
    changelog: ['Added DirectWave sample presets', 'Export stems in 24-bit 48kHz audio'],
    createdAt: '2026-08-12T10:00:00.000Z',
    updatedAt: '2026-08-31T11:00:00.000Z'
  },
  {
    id: 'apk-49',
    title: 'Canva Graphic Design & Social Media Studio Pro',
    description: 'Design Facebook banners, YouTube thumbnails, Instagram reels, posters, presentations with millions of templates.',
    detailedNotes: 'Easy drag-and-drop graphic studio with AI background remover, brand kit fonts, animation creator, and high resolution PDF/PNG export.',
    thumbnail: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/canva-pro-v2.270.apk',
    fileName: 'canva-pro-v2.270.apk',
    fileSize: '54.0 MB',
    version: 'v2.270.0',
    category: 'Productivity & Utilities',
    type: 'apk',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    downloadsCount: 38900,
    published: true,
    developer: 'Canva Pty Ltd',
    packageId: 'com.canva.editor',
    minAndroidVersion: 'Android 8.0+',
    sha256Checksum: '49',
    changelog: ['Magic Eraser AI photo tool', 'Bengali typography templates collection'],
    createdAt: '2026-08-01T10:00:00.000Z',
    updatedAt: '2026-08-25T14:00:00.000Z'
  },
  {
    id: 'apk-50',
    title: 'Stumble Guys Skin Visualizer & Map Companion',
    description: '3D skin previewer, tournament countdown timer, obstacle course shortcut guides, and custom party room finder.',
    detailedNotes: 'Master obstacle jumps and learn high-speed shortcuts across all official maps with frame-by-frame jump timing guides.',
    thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=600&q=80',
    fileUrl: '/uploads/stumble-companion-v2.2.apk',
    fileName: 'stumble-companion-v2.2.apk',
    fileSize: '21.0 MB',
    version: 'v2.2.1',
    category: 'Online Gaming & Esports',
    type: 'apk',
    accessType: 'FREE',
    price: 0,
    currency: 'BDT',
    downloadsCount: 11900,
    published: true,
    developer: 'Stumble Fans Studio',
    packageId: 'com.stumblefans.companion',
    minAndroidVersion: 'Android 7.0+',
    sha256Checksum: '50',
    changelog: ['New laser dash map jump timings added', 'Emote animation 3D viewer'],
    createdAt: '2026-08-14T12:00:00.000Z',
    updatedAt: '2026-08-30T18:00:00.000Z'
  }
];
